export const en = {
    curriculum: {
        manage: 'Manage curriculum',
        heading: 'Curriculum builder', description: 'Organize sections, lessons and resources for this course.', sectionCount: '{count} sections', lessonCount: '{count} lessons', addSection: 'Add section', addLesson: 'Add lesson', editLesson: 'Edit lesson', lessons: 'Lessons', resources: 'Resources', empty: 'This course has no sections yet.', noLessons: 'No lessons in this section.', noResources: 'No resources for this lesson.', type: 'Lesson type', types: { text: 'Text', video: 'Video', file: 'File', link: 'Link' }, durationSeconds: 'Duration (seconds)', textContent: 'Text content', plainText: 'Plain text is displayed safely; HTML is not executed.', videoProvider: 'Video provider', videoId: 'Video ID', videoUrl: 'Video URL', linkUrl: 'External URL', publishedLesson: 'Published lesson', draftLesson: 'Draft lesson', publicPreview: 'Public preview', enrolledOnly: 'Enrolled learners only', previewExplanation: 'Preview is distinct from course publication. Public access still follows server rules.', fileProvisioning: 'File lessons may be drafted here. A trusted server operator must provision file bytes; this form cannot upload them.', addLink: 'Add external link', noUploadEndpoint: 'The backend currently supports resource references and links, not browser file upload or an admin file download endpoint.', downloadReady: 'Protected file available', externalLink: 'External link', noFileAvailable: 'No available file', downloadable: 'Downloadable', moveEarlier: 'Move earlier', moveLater: 'Move later', confirmDeleteSection: 'Delete this section and its {count} lessons? This may affect learning records.', confirmDeleteLesson: 'Delete this lesson? It will be soft-deleted.', confirmDeleteResource: 'Delete this resource?',
    },
    packages: {
        adminHeading: 'Packages & learning paths', adminDescription: 'Manage package metadata and current course composition.', add: 'New package', edit: 'Edit package', empty: 'No packages match these filters.', search: 'Search packages', type: 'Type', allTypes: 'All types', types: { package: 'Package', learning_path: 'Learning path' }, statuses: { draft: 'Draft', published: 'Published', hidden: 'Hidden', archived: 'Archived' }, courseCount: 'Courses', courses: 'Courses', confirmDelete: 'Delete this package? It will be soft-deleted.', formDescription: 'Set the package price, access period and publication state.', manageCourses: 'Manage courses', futurePurchases: 'Changes to current package courses apply to future purchases only. Historical orders and access grants are not rewritten.', publishNote: 'Publishing is permission-controlled. Only currently published, available courses appear in the public package API.', saveFirst: 'Save the package, then add courses.', addCourse: 'Add course', searchCourse: 'Search courses', searchAction: 'Search', optionError: 'Unable to load course options.', selectCourse: 'Select a course', alreadyAdded: 'already added', requiredCourse: 'Required course', optionalCourse: 'Optional course', loadMoreCourses: 'Load more courses', currentCourses: 'Current course composition', noSelectedCourses: 'No courses are currently selected.', unavailableCourse: 'Course unavailable', makeOptional: 'Make optional', makeRequired: 'Make required', confirmRemoveCourse: 'Remove this course from the current package? Historical purchases will not change.',
    },
};

export const ar = {
    curriculum: {
        manage: 'إدارة المنهج',
        heading: 'بناء المنهج', description: 'نظّم أقسام الدورة ودروسها ومواردها.', sectionCount: '{count} أقسام', lessonCount: '{count} دروس', addSection: 'إضافة قسم', addLesson: 'إضافة درس', editLesson: 'تعديل الدرس', lessons: 'الدروس', resources: 'الموارد', empty: 'لا توجد أقسام في هذه الدورة بعد.', noLessons: 'لا توجد دروس في هذا القسم.', noResources: 'لا توجد موارد لهذا الدرس.', type: 'نوع الدرس', types: { text: 'نصي', video: 'فيديو', file: 'ملف', link: 'رابط' }, durationSeconds: 'المدة بالثواني', textContent: 'المحتوى النصي', plainText: 'يُعرض النص بأمان؛ لا تُنفذ وسوم HTML.', videoProvider: 'مزود الفيديو', videoId: 'معرّف الفيديو', videoUrl: 'رابط الفيديو', linkUrl: 'الرابط الخارجي', publishedLesson: 'درس منشور', draftLesson: 'درس مسودة', publicPreview: 'معاينة عامة', enrolledOnly: 'للمسجلين فقط', previewExplanation: 'المعاينة تختلف عن نشر الدورة؛ الوصول العام ما زال يخضع لقواعد الخادم.', fileProvisioning: 'يمكن إعداد درس ملف كمسودة هنا. يجب توفير الملف من مشغّل موثوق؛ هذه الواجهة لا ترفعه.', addLink: 'إضافة رابط خارجي', noUploadEndpoint: 'يدعم الخادم مراجع الموارد والروابط، ولا يوفر حاليًا رفع ملف من المتصفح أو تنزيلًا إداريًا للملف.', downloadReady: 'الملف المحمي متاح', externalLink: 'رابط خارجي', noFileAvailable: 'لا يوجد ملف متاح', downloadable: 'قابل للتنزيل', moveEarlier: 'نقل للأعلى', moveLater: 'نقل للأسفل', confirmDeleteSection: 'حذف هذا القسم ودروسه وعددها {count}؟ قد تتأثر سجلات التعلم.', confirmDeleteLesson: 'حذف هذا الدرس حذفًا مرنًا؟', confirmDeleteResource: 'حذف هذا المورد؟',
    },
    packages: {
        adminHeading: 'الباقات والمسارات التعليمية', adminDescription: 'أدر بيانات الباقات وتركيب الدورات الحالي.', add: 'باقة جديدة', edit: 'تعديل الباقة', empty: 'لا توجد باقات تطابق التصفية.', search: 'البحث في الباقات', type: 'النوع', allTypes: 'كل الأنواع', types: { package: 'باقة', learning_path: 'مسار تعليمي' }, statuses: { draft: 'مسودة', published: 'منشورة', hidden: 'مخفية', archived: 'مؤرشفة' }, courseCount: 'عدد الدورات', courses: 'الدورات', confirmDelete: 'حذف هذه الباقة حذفًا مرنًا؟', formDescription: 'حدد سعر الباقة ومدة الوصول وحالة النشر.', manageCourses: 'إدارة الدورات', futurePurchases: 'تغييرات دورات الباقة الحالية تسري على المشتريات المستقبلية فقط؛ لا تُعاد كتابة الطلبات أو منح الوصول السابقة.', publishNote: 'النشر محكوم بالصلاحيات. تظهر في واجهة الباقة العامة الدورات المنشورة والمتاحة حاليًا فقط.', saveFirst: 'احفظ الباقة ثم أضف الدورات.', addCourse: 'إضافة دورة', searchCourse: 'البحث في الدورات', searchAction: 'بحث', optionError: 'تعذر تحميل خيارات الدورات.', selectCourse: 'اختر دورة', alreadyAdded: 'مضافة مسبقًا', requiredCourse: 'دورة أساسية', optionalCourse: 'دورة اختيارية', loadMoreCourses: 'تحميل دورات إضافية', currentCourses: 'الدورات الحالية في الباقة', noSelectedCourses: 'لا توجد دورات مضافة حاليًا.', unavailableCourse: 'الدورة غير متاحة', makeOptional: 'جعلها اختيارية', makeRequired: 'جعلها أساسية', confirmRemoveCourse: 'إزالة هذه الدورة من الباقة الحالية؟ لن تتغير المشتريات السابقة.',
    },
};
