export const en = {
    totalUsers: 'Total users', totalStudents: 'Total students', totalInstructors: 'Total instructors', userListDescription: 'Find accounts and manage access safely.', instructorListDescription: 'Manage instructor accounts and public profiles.', instructorFormDescription: 'Account access and instructor profile are managed together.', addUser: 'New user', editUser: 'Edit user', addInstructor: 'New instructor', editInstructor: 'Edit instructor', searchUsers: 'Search users', searchInstructors: 'Search instructors', searchAction: 'Search', loadMoreInstructors: 'Load more instructors', selectInstructor: 'Select an instructor', instructorLoadError: 'Unable to load instructors.', allRoles: 'All roles', roles: 'Roles', email: 'Email', created: 'Created', emptyUsers: 'No users match these filters.', emptyInstructors: 'No instructors match this search.', password: 'Password', passwordConfirmation: 'Confirm password', changePassword: 'Change password', blankPassword: 'Leave blank to keep the current password.', confirmRoleChange: 'Change this user’s roles? This may change their access.', instructorRoleNote: 'Create instructor accounts from the Instructors section.', instructorAccount: 'Instructor account', instructorProfile: 'Instructor profile', jobTitle: 'Job title', yearsExperience: 'Years of experience', shortBio: 'Short bio', bio: 'Biography', specialties: 'Specialties', onePerLine: 'One specialty per line.', linkedin_url: 'LinkedIn URL', facebook_url: 'Facebook URL', instagram_url: 'Instagram URL', website_url: 'Website URL', serverCurrency: 'server currency',
    dashboard: 'Administration', dashboardDescription: 'A clear view of the content you are permitted to manage.', categories: 'Categories', courses: 'Courses', users: 'Users', instructors: 'Instructors', totalCategories: 'Total categories', totalCourses: 'Total courses', publishedCourses: 'Published courses', draftCourses: 'Draft courses', noMetrics: 'No summary metrics are available with your current permissions.', summaryError: 'Unable to load some summary metrics.',
    categoryListDescription: 'Organize the learning catalog and its category hierarchy.', courseListDescription: 'Manage course metadata and publishing state.', addCategory: 'New category', editCategory: 'Edit category', addCourse: 'New course', editCourse: 'Edit course',
    name: 'Name', slug: 'Slug', description: 'Description', parent: 'Parent category', noParent: 'Top-level category', loadMoreCategories: 'Load more categories', image: 'Image URL or path', icon: 'Icon name', sortOrder: 'Display order', active: 'Active', inactive: 'Inactive', status: 'Status', level: 'Level', category: 'Category', instructor: 'Instructor', title: 'Title', shortDescription: 'Short description', thumbnail: 'Thumbnail URL or path', promoVideo: 'Promo video URL', language: 'Content language', duration: 'Duration in minutes', access: 'Access duration', lifetime: 'Lifetime access', limited: 'Limited access', accessDays: 'Access days', accessNote: 'Changing this course setting does not rewrite historical access grants.', price: 'Price', comparePrice: 'Compare price', currency: 'Currency', certificate: 'Certificates enabled', discussion: 'Discussions enabled', featured: 'Featured', publishedAt: 'Publish date', basic: 'Basic information', classification: 'Classification', pricing: 'Pricing and access', publishing: 'Publishing', media: 'Media', settings: 'Settings',
    search: 'Search courses', allStatuses: 'All statuses', allCategories: 'All categories', allLevels: 'All levels', filters: 'Filters', apply: 'Apply filters', clear: 'Clear filters', save: 'Save changes', create: 'Create', cancel: 'Cancel', edit: 'Edit', delete: 'Delete', deleting: 'Deleting…', confirmDeleteCategory: 'Delete this category? Categories with children or courses cannot be deleted.', confirmDeleteCourse: 'Delete this course? It will be soft-deleted.', deleteBlocked: 'This category cannot be deleted while it has child categories or courses.', notAllowed: 'You do not have permission for this action.', validation: 'Review the highlighted fields.', loadError: 'Unable to load management data.', saveError: 'Unable to save these changes.', emptyCategories: 'No categories found.', emptyCourses: 'No courses match these filters.', required: 'This field is required.', slugHint: 'Enter a unique slug using letters, numbers, dashes or underscores.', decimalHint: 'Use a decimal amount; currency is set by the server.', updated: 'Updated', new: 'New',
    discountStart: 'Discount starts', discountEnd: 'Discount ends', learning_outcomes: 'Learning outcomes (one per line)', requirements: 'Requirements (one per line)', target_audiences: 'Target audiences (one per line)', required_tools: 'Required tools (one per line)', parentSafety: 'You can change the parent; the server rejects this category or its descendants.', positiveDays: 'Enter a positive whole number of days.',
    courseStatus: { draft: 'Draft', published: 'Published', hidden: 'Hidden', coming_soon: 'Coming soon', archived: 'Archived' },
};

export const ar = {
    totalUsers: 'إجمالي المستخدمين', totalStudents: 'إجمالي الطلاب', totalInstructors: 'إجمالي المدربين', userListDescription: 'ابحث في الحسابات وأدر صلاحياتها بأمان.', instructorListDescription: 'إدارة حسابات المدربين وملفاتهم التعريفية.', instructorFormDescription: 'تُدار بيانات الحساب والملف التعريفي معًا.', addUser: 'مستخدم جديد', editUser: 'تعديل المستخدم', addInstructor: 'مدرب جديد', editInstructor: 'تعديل المدرب', searchUsers: 'البحث في المستخدمين', searchInstructors: 'البحث في المدربين', searchAction: 'بحث', loadMoreInstructors: 'تحميل مدربين إضافيين', selectInstructor: 'اختر مدربًا', instructorLoadError: 'تعذر تحميل المدربين.', allRoles: 'كل الأدوار', roles: 'الأدوار', email: 'البريد الإلكتروني', created: 'تاريخ الإنشاء', emptyUsers: 'لا يوجد مستخدمون يطابقون التصفية.', emptyInstructors: 'لا يوجد مدربون يطابقون البحث.', password: 'كلمة المرور', passwordConfirmation: 'تأكيد كلمة المرور', changePassword: 'تغيير كلمة المرور', blankPassword: 'اتركها فارغة للإبقاء على كلمة المرور الحالية.', confirmRoleChange: 'تغيير أدوار هذا المستخدم؟ قد تتغير صلاحياته.', instructorRoleNote: 'أنشئ حساب المدرب من قسم المدربين.', instructorAccount: 'حساب المدرب', instructorProfile: 'ملف المدرب', jobTitle: 'المسمى المهني', yearsExperience: 'سنوات الخبرة', shortBio: 'نبذة قصيرة', bio: 'السيرة', specialties: 'التخصصات', onePerLine: 'تخصص واحد في كل سطر.', linkedin_url: 'رابط لينكدإن', facebook_url: 'رابط فيسبوك', instagram_url: 'رابط إنستغرام', website_url: 'رابط الموقع', serverCurrency: 'عملة الخادم',
    dashboard: 'الإدارة', dashboardDescription: 'نظرة واضحة على المحتوى المسموح لك بإدارته.', categories: 'التصنيفات', courses: 'الدورات', users: 'المستخدمون', instructors: 'المدربون', totalCategories: 'إجمالي التصنيفات', totalCourses: 'إجمالي الدورات', publishedCourses: 'الدورات المنشورة', draftCourses: 'الدورات المسودة', noMetrics: 'لا تتوفر مؤشرات ملخصة ضمن صلاحياتك الحالية.', summaryError: 'تعذر تحميل بعض مؤشرات الملخص.',
    categoryListDescription: 'نظّم كتالوج التعلّم وتسلسل التصنيفات.', courseListDescription: 'أدر بيانات الدورات وحالة النشر.', addCategory: 'تصنيف جديد', editCategory: 'تعديل التصنيف', addCourse: 'دورة جديدة', editCourse: 'تعديل الدورة',
    name: 'الاسم', slug: 'المعرّف النصي', description: 'الوصف', parent: 'التصنيف الأب', noParent: 'تصنيف رئيسي', loadMoreCategories: 'تحميل تصنيفات إضافية', image: 'رابط أو مسار الصورة', icon: 'اسم الأيقونة', sortOrder: 'ترتيب العرض', active: 'نشط', inactive: 'غير نشط', status: 'الحالة', level: 'المستوى', category: 'التصنيف', instructor: 'المدرب', title: 'العنوان', shortDescription: 'وصف مختصر', thumbnail: 'رابط أو مسار الغلاف', promoVideo: 'رابط الفيديو الترويجي', language: 'لغة المحتوى', duration: 'المدة بالدقائق', access: 'مدة الوصول', lifetime: 'وصول دائم', limited: 'وصول محدد', accessDays: 'أيام الوصول', accessNote: 'تغيير هذا الإعداد لا يعدّل منح الوصول التاريخية.', price: 'السعر', comparePrice: 'السعر المقارن', currency: 'العملة', certificate: 'تفعيل الشهادات', discussion: 'تفعيل النقاشات', featured: 'مميزة', publishedAt: 'تاريخ النشر', basic: 'المعلومات الأساسية', classification: 'التصنيف', pricing: 'السعر والوصول', publishing: 'النشر', media: 'الوسائط', settings: 'الإعدادات',
    search: 'البحث في الدورات', allStatuses: 'كل الحالات', allCategories: 'كل التصنيفات', allLevels: 'كل المستويات', filters: 'عوامل التصفية', apply: 'تطبيق التصفية', clear: 'مسح التصفية', save: 'حفظ التغييرات', create: 'إنشاء', cancel: 'إلغاء', edit: 'تعديل', delete: 'حذف', deleting: 'جارٍ الحذف…', confirmDeleteCategory: 'حذف هذا التصنيف؟ لا يمكن حذف تصنيف يرتبط به تصنيفات فرعية أو دورات.', confirmDeleteCourse: 'حذف هذه الدورة؟ ستُحذف حذفًا مرنًا.', deleteBlocked: 'لا يمكن حذف التصنيف ما دامت له تصنيفات فرعية أو دورات.', notAllowed: 'لا تملك صلاحية هذا الإجراء.', validation: 'راجع الحقول المحددة.', loadError: 'تعذر تحميل بيانات الإدارة.', saveError: 'تعذر حفظ التغييرات.', emptyCategories: 'لم نجد تصنيفات.', emptyCourses: 'لا توجد دورات تطابق هذه التصفية.', required: 'هذا الحقل مطلوب.', slugHint: 'أدخل معرفًا فريدًا بحروف أو أرقام أو شرطات أو شرطات سفلية.', decimalHint: 'استخدم قيمة عشرية؛ يحدد الخادم العملة.', updated: 'آخر تحديث', new: 'جديد',
    discountStart: 'بداية الخصم', discountEnd: 'نهاية الخصم', learning_outcomes: 'مخرجات التعلّم (عنصر لكل سطر)', requirements: 'المتطلبات (عنصر لكل سطر)', target_audiences: 'الفئات المستهدفة (عنصر لكل سطر)', required_tools: 'الأدوات المطلوبة (عنصر لكل سطر)', parentSafety: 'يمكن تغيير التصنيف الأب؛ سيرفض الخادم اختيار التصنيف نفسه أو أحد تصنيفاته الفرعية.', positiveDays: 'أدخل عدد أيام صحيحًا أكبر من صفر.',
    courseStatus: { draft: 'مسودة', published: 'منشورة', hidden: 'مخفية', coming_soon: 'قريبًا', archived: 'مؤرشفة' },
};
