export const en = {
    curriculum: {
        videoNotConfigured: 'Bunny Stream is not configured on this server. Ask an administrator to enable it; do not paste keys here.',
        videoRetryCleanup: 'Retry remote cleanup',
        videoRequestTimeout: 'The upload request timed out. Check your connection, then choose the same file to resume. If it continues, inspect the failed request in the browser Network tab.',
        videoUploadStages: { preparing: 'Creating a secure upload session…', connecting: 'Connecting directly to Bunny Stream…', transferring: 'Sending video to Bunny Stream…', processing: 'Upload complete; checking video processing…' },
        videoSelectedFile: 'File', videoProcessingTitle: 'Upload complete — preparing your video', videoReadyTitle: 'Video ready to use', videoProcessingProgress: 'Video processing', videoProcessingStarting: 'Waiting for processing to start',
        videoPublishAfterReady: 'You can publish this lesson after video processing is complete.',
        videoStatusHelp: { creating: 'Preparing a secure upload session. Please wait.', uncertain: 'The upload session could not be confirmed. Contact an administrator before trying again.', uploading: 'The upload is still in progress or being confirmed. If it stopped, choose the same file to resume.', processing: 'The file has finished uploading. The video is being prepared automatically; you do not need to upload it again.', ready: 'The video is ready. To make this lesson available, select “Published lesson” below and save changes. Learner access also depends on course publication and permissions.', readyPublished: 'The video is ready and this lesson is published. Learner access still depends on course publication and permissions.', failed: 'Video processing failed. Remove this upload before trying a new file.', retired: 'This video was replaced. Remove it if cleanup is needed.', deleted: 'The video was removed. You can choose another file.', cleanup_failed: 'Remote removal failed. Retry cleanup before uploading another video.' },
        videoPublishBeforeReady: 'Upload and process the protected video before publishing this lesson.',
        videoUploadHeading: 'Protected lesson video', videoUploadHint: 'Choose an MP4, MOV or WebM file. Uploads go directly to Bunny Stream and can resume after interruption.', videoChooseBeforeCreate: 'Choose an MP4, MOV or WebM file now. Creating the lesson will save it as a draft and start the upload automatically. You can also add the video later.', createAndUpload: 'Create and upload video', videoChooseFile: 'Video file', videoUpload: 'Upload video', videoResume: 'Resume upload', videoResumeHint: 'Choose the same file to resume this upload.', videoInvalidFile: 'Choose a supported video file within the configured size limit.', videoUploadError: 'Unable to upload the video. Choose the same file to retry.', videoStatusError: 'Unable to check video processing. Try again later.', videoRemoveConfirm: 'Remove this protected video? Learners will lose access to it.', videoRemove: 'Remove video', videoRemoveError: 'Unable to remove the video.', videoCleanupFailed: 'Playback was removed, but remote cleanup failed. Retry removal or ask an administrator.', videoPreview: 'Preview protected video', videoPreviewError: 'Protected preview is unavailable.', videoStates: { creating: 'Creating', uncertain: 'Creation uncertain — contact an administrator', uploading: 'Uploading', processing: 'Processing', ready: 'Ready', failed: 'Failed', retired: 'Retired', deleted: 'Removed', cleanup_failed: 'Remote cleanup needed' },
        manage: 'Manage curriculum', loadMoreOptions: 'Load more options',
        addFile: 'Upload file', selectFile: 'Select a file', downloadFile: 'Download file',
        protectedVideoAssetKey: 'Private video reference', protectedVideoHint: 'Enter a reference provisioned by a trusted operator. A public URL cannot secure a paid lesson.', protectedVideoUnavailable: 'Protected video playback is not configured. Even if this lesson is published, learners cannot play it until a video provider is connected and verified.', operatorVideoSetup: 'Operator-provided video setup', previewVideoUrl: 'Public preview video URL',
        heading: 'Curriculum builder', description: 'Organize sections, lessons and resources for this course.', sectionCount: '{count} sections', lessonCount: '{count} lessons', addSection: 'Add section', addLesson: 'Add lesson', editLesson: 'Edit lesson', lessons: 'Lessons', resources: 'Resources', empty: 'This course has no sections yet.', noLessons: 'No lessons in this section.', noResources: 'No resources for this lesson.', type: 'Lesson type', types: { text: 'Text', video: 'Video', file: 'File', link: 'Link' }, durationSeconds: 'Duration (seconds)', textContent: 'Text content', plainText: 'Plain text is displayed safely; HTML is not executed.', videoProvider: 'Video provider', videoId: 'Video ID', videoUrl: 'Video URL', linkUrl: 'External URL', publishedLesson: 'Published lesson', draftLesson: 'Draft lesson', publicPreview: 'Public preview', enrolledOnly: 'Enrolled learners only', previewExplanation: 'Preview is distinct from course publication. Public access still follows server rules.', fileProvisioning: 'File lessons may be drafted here. A trusted server operator must provision file bytes; this form cannot upload them.', addLink: 'Add external link', noUploadEndpoint: 'The backend currently supports resource references and links, not browser file upload or an admin file download endpoint.', downloadReady: 'Protected file available', externalLink: 'External link', noFileAvailable: 'No available file', downloadable: 'Downloadable', moveEarlier: 'Move earlier', moveLater: 'Move later', confirmDeleteSection: 'Delete this section and its {count} lessons? This may affect learning records.', confirmDeleteLesson: 'Delete this lesson? It will be soft-deleted.', confirmDeleteResource: 'Delete this resource?',
    },
    packages: {
        adminHeading: 'Packages & learning paths', adminDescription: 'Manage package metadata and current course composition.', add: 'New package', edit: 'Edit package', empty: 'No packages match these filters.', search: 'Search packages', type: 'Type', allTypes: 'All types', types: { package: 'Package', learning_path: 'Learning path' }, statuses: { draft: 'Draft', published: 'Published', hidden: 'Hidden', archived: 'Archived' }, courseCount: 'Courses', courses: 'Courses', confirmDelete: 'Delete this package? It will be soft-deleted.', formDescription: 'Set the package price, access period and publication state.', manageCourses: 'Manage courses', futurePurchases: 'Changes to current package courses apply to future purchases only. Historical orders and access grants are not rewritten.', publishNote: 'Publishing is permission-controlled. Only currently published, available courses appear in the public package API.', saveFirst: 'Save the package, then add courses.', addCourse: 'Add course', searchCourse: 'Search courses', searchAction: 'Search', optionError: 'Unable to load course options.', selectCourse: 'Select a course', alreadyAdded: 'already added', requiredCourse: 'Required course', optionalCourse: 'Optional course', loadMoreCourses: 'Load more courses', currentCourses: 'Current course composition', noSelectedCourses: 'No courses are currently selected.', unavailableCourse: 'Course unavailable', makeOptional: 'Make optional', makeRequired: 'Make required', confirmRemoveCourse: 'Remove this course from the current package? Historical purchases will not change.',
    },
};

export const ar = {
    curriculum: {
        videoNotConfigured: 'لم يُهيّأ Bunny Stream على هذا الخادم. اطلب من الإدارة تفعيله؛ لا تضع المفاتيح هنا.',
        videoRetryCleanup: 'إعادة محاولة الحذف من المزوّد',
        videoRequestTimeout: 'انتهت مهلة طلب الرفع. تحقّق من الاتصال ثم اختر الملف نفسه للاستئناف. إذا تكرر، افحص الطلب الفاشل في تبويب Network بالمتصفح.',
        videoUploadStages: { preparing: 'جارٍ إنشاء جلسة رفع آمنة…', connecting: 'جارٍ الاتصال المباشر بـ Bunny Stream…', transferring: 'جارٍ إرسال الفيديو إلى Bunny Stream…', processing: 'اكتمل الرفع؛ جارٍ فحص معالجة الفيديو…' },
        videoSelectedFile: 'الملف', videoProcessingTitle: 'اكتمل الرفع — جارٍ تجهيز الفيديو', videoReadyTitle: 'الفيديو جاهز للاستخدام', videoProcessingProgress: 'معالجة الفيديو', videoProcessingStarting: 'بانتظار بدء معالجة الفيديو',
        videoPublishAfterReady: 'يمكنك نشر هذا الدرس بعد اكتمال معالجة الفيديو.',
        videoStatusHelp: { creating: 'جارٍ تجهيز جلسة رفع آمنة. انتظر قليلًا.', uncertain: 'تعذّر تأكيد جلسة الرفع. تواصل مع الإدارة قبل إعادة المحاولة.', uploading: 'الرفع أو تأكيد استلام الملف ما زال جاريًا. إذا توقف، اختر الملف نفسه للاستئناف.', processing: 'اكتمل رفع الملف. يجري تجهيز الفيديو تلقائيًا؛ لا حاجة إلى إعادة رفعه.', ready: 'الفيديو جاهز. لإتاحة الدرس، فعّل «درس منشور» أدناه ثم اضغط «حفظ التغييرات». وصول الطلاب يعتمد أيضًا على نشر الدورة وصلاحياتهم.', readyPublished: 'الفيديو جاهز والدرس منشور. وصول الطلاب يعتمد أيضًا على نشر الدورة وصلاحياتهم.', failed: 'فشلت معالجة الفيديو. أزل هذا الرفع قبل تجربة ملف جديد.', retired: 'استُبدل هذا الفيديو. أزله إذا لزم تنظيفه.', deleted: 'أُزيل الفيديو. يمكنك اختيار ملف جديد.', cleanup_failed: 'تعذّر الحذف من المزوّد. أعد محاولة الحذف قبل رفع فيديو آخر.' },
        videoPublishBeforeReady: 'ارفع الفيديو المحمي وانتظر اكتمال معالجته قبل نشر هذا الدرس.',
        videoUploadHeading: 'فيديو الدرس المحمي', videoUploadHint: 'اختر ملف MP4 أو MOV أو WebM. يُرفع مباشرة إلى Bunny Stream ويمكن استئنافه بعد الانقطاع.', videoChooseBeforeCreate: 'اختر ملف MP4 أو MOV أو WebM الآن. عند إنشاء الدرس سيُحفظ كمسودة ويبدأ رفع الفيديو تلقائيًا. ويمكنك إضافة الفيديو لاحقًا.', createAndUpload: 'إنشاء الدرس ورفع الفيديو', videoChooseFile: 'ملف الفيديو', videoUpload: 'رفع الفيديو', videoResume: 'استئناف الرفع', videoResumeHint: 'اختر الملف نفسه لاستئناف الرفع.', videoInvalidFile: 'اختر ملف فيديو مدعومًا ضمن الحد المسموح.', videoUploadError: 'تعذّر رفع الفيديو. اختر الملف نفسه لإعادة المحاولة.', videoStatusError: 'تعذّر فحص معالجة الفيديو. حاول لاحقًا.', videoRemoveConfirm: 'إزالة هذا الفيديو المحمي؟ سيفقد المتدربون الوصول إليه.', videoRemove: 'إزالة الفيديو', videoRemoveError: 'تعذّرت إزالة الفيديو.', videoCleanupFailed: 'أُوقف التشغيل، لكن حذف الملف من المزوّد فشل. أعد المحاولة أو تواصل مع الإدارة.', videoPreview: 'معاينة الفيديو المحمي', videoPreviewError: 'معاينة الفيديو المحمي غير متاحة.', videoStates: { creating: 'جارٍ الإنشاء', uncertain: 'حالة الإنشاء غير مؤكدة — تواصل مع الإدارة', uploading: 'جارٍ الرفع', processing: 'قيد المعالجة', ready: 'جاهز', failed: 'فشل', retired: 'مستبدل', deleted: 'أُزيل', cleanup_failed: 'يحتاج حذفًا من المزوّد' },
        manage: 'إدارة المنهج', loadMoreOptions: 'تحميل خيارات إضافية',
        addFile: 'رفع ملف', selectFile: 'اختر ملفًا', downloadFile: 'تنزيل الملف',
        protectedVideoAssetKey: 'مرجع الفيديو الخاص', protectedVideoHint: 'أدخل مرجعًا يجهّزه مشغّل موثوق. الرابط العام لا يحمي درسًا مدفوعًا.', protectedVideoUnavailable: 'تشغيل الفيديو المحمي غير مُهيأ. حتى لو نُشر هذا الدرس، لن يستطيع المتدربون تشغيله حتى يُربط مزود فيديو ويُتحقق منه.', operatorVideoSetup: 'إعداد الفيديو بواسطة المشغّل', previewVideoUrl: 'رابط فيديو المعاينة العامة',
        heading: 'بناء المنهج', description: 'نظّم أقسام الدورة ودروسها ومواردها.', sectionCount: '{count} أقسام', lessonCount: '{count} دروس', addSection: 'إضافة قسم', addLesson: 'إضافة درس', editLesson: 'تعديل الدرس', lessons: 'الدروس', resources: 'الموارد', empty: 'لا توجد أقسام في هذه الدورة بعد.', noLessons: 'لا توجد دروس في هذا القسم.', noResources: 'لا توجد موارد لهذا الدرس.', type: 'نوع الدرس', types: { text: 'نصي', video: 'فيديو', file: 'ملف', link: 'رابط' }, durationSeconds: 'المدة بالثواني', textContent: 'المحتوى النصي', plainText: 'يُعرض النص بأمان؛ لا تُنفذ وسوم HTML.', videoProvider: 'مزود الفيديو', videoId: 'معرّف الفيديو', videoUrl: 'رابط الفيديو', linkUrl: 'الرابط الخارجي', publishedLesson: 'درس منشور', draftLesson: 'درس مسودة', publicPreview: 'معاينة عامة', enrolledOnly: 'للمسجلين فقط', previewExplanation: 'المعاينة تختلف عن نشر الدورة؛ الوصول العام ما زال يخضع لقواعد الخادم.', fileProvisioning: 'يمكن إعداد درس ملف كمسودة هنا. يجب توفير الملف من مشغّل موثوق؛ هذه الواجهة لا ترفعه.', addLink: 'إضافة رابط خارجي', noUploadEndpoint: 'يدعم الخادم مراجع الموارد والروابط، ولا يوفر حاليًا رفع ملف من المتصفح أو تنزيلًا إداريًا للملف.', downloadReady: 'الملف المحمي متاح', externalLink: 'رابط خارجي', noFileAvailable: 'لا يوجد ملف متاح', downloadable: 'قابل للتنزيل', moveEarlier: 'نقل للأعلى', moveLater: 'نقل للأسفل', confirmDeleteSection: 'حذف هذا القسم ودروسه وعددها {count}؟ قد تتأثر سجلات التعلم.', confirmDeleteLesson: 'حذف هذا الدرس حذفًا مرنًا؟', confirmDeleteResource: 'حذف هذا المورد؟',
    },
    packages: {
        adminHeading: 'الباقات والمسارات التعليمية', adminDescription: 'أدر بيانات الباقات وتركيب الدورات الحالي.', add: 'باقة جديدة', edit: 'تعديل الباقة', empty: 'لا توجد باقات تطابق التصفية.', search: 'البحث في الباقات', type: 'النوع', allTypes: 'كل الأنواع', types: { package: 'باقة', learning_path: 'مسار تعليمي' }, statuses: { draft: 'مسودة', published: 'منشورة', hidden: 'مخفية', archived: 'مؤرشفة' }, courseCount: 'عدد الدورات', courses: 'الدورات', confirmDelete: 'حذف هذه الباقة حذفًا مرنًا؟', formDescription: 'حدد سعر الباقة ومدة الوصول وحالة النشر.', manageCourses: 'إدارة الدورات', futurePurchases: 'تغييرات دورات الباقة الحالية تسري على المشتريات المستقبلية فقط؛ لا تُعاد كتابة الطلبات أو منح الوصول السابقة.', publishNote: 'النشر محكوم بالصلاحيات. تظهر في واجهة الباقة العامة الدورات المنشورة والمتاحة حاليًا فقط.', saveFirst: 'احفظ الباقة ثم أضف الدورات.', addCourse: 'إضافة دورة', searchCourse: 'البحث في الدورات', searchAction: 'بحث', optionError: 'تعذر تحميل خيارات الدورات.', selectCourse: 'اختر دورة', alreadyAdded: 'مضافة مسبقًا', requiredCourse: 'دورة أساسية', optionalCourse: 'دورة اختيارية', loadMoreCourses: 'تحميل دورات إضافية', currentCourses: 'الدورات الحالية في الباقة', noSelectedCourses: 'لا توجد دورات مضافة حاليًا.', unavailableCourse: 'الدورة غير متاحة', makeOptional: 'جعلها اختيارية', makeRequired: 'جعلها أساسية', confirmRemoveCourse: 'إزالة هذه الدورة من الباقة الحالية؟ لن تتغير المشتريات السابقة.',
    },
};
