import { en as commerce } from './commerce';
import { en as learning } from './learning';
import { en as assessments } from './assessments';
import { en as reviewsSupport } from './reviews-support';
import { en as admin } from './admin';
import { en as adminContent } from './admin-content';
import { en as operations } from './operations';
import { en as instructor } from './instructor';
import { en as certificatePolicy } from './certificate-policy';
import { en as path } from './sequential';
import { en as audit } from './audit';
import { en as phase15f } from './phase15f';
import { en as reports } from './reports';
import { en as rolePermissions } from './role-permissions';
import { en as assessmentAuthoring } from './assessment-authoring';

export default {
    commerce,
    learning,
    assessments: { ...assessments, reasons: { ...assessments.reasons, certificate_configuration_missing: 'Certificate requirements have not been configured.', final_exam_unavailable: 'The final exam is unavailable.', final_exam_incomplete: 'Complete the final exam first.', final_exam_failed: 'The final exam passing score has not been met.', required_assignments_incomplete: 'Complete and pass the required assignments.', admin_approval_pending: 'Administrator approval is pending.' } },
    ...reviewsSupport,
    admin,
    curriculum: adminContent.curriculum,
    operations,
    instructor,
    certificatePolicy,
    path,
    audit,
    reports,
    rolePermissions,
    assessmentAuthoring,
    ...phase15f,
    brand: {
        name: 'JCEC Academy', tagline: 'Learn today… build a better tomorrow', promise: 'Build professional skills that create a real difference in your future.', description: 'An Arabic-first professional learning platform bringing specialized content, assessment, and practical progress into one experience.',
    },
    common: {
        login: 'Sign in', logout: 'Sign out', dashboard: 'Dashboard', home: 'Home', language: 'العربية', menu: 'Open menu', close: 'Close', upcoming: 'Coming soon', backHome: 'Back home', loading: 'Loading…', retry: 'Try again', viewAll: 'View all', explore: 'Explore now', learnMore: 'Learn more', previous: 'Previous', next: 'Next', page: 'Page {current} of {total}', search: 'Search', reset: 'Reset', apply: 'Apply', notSpecified: 'Not specified', skipContent: 'Skip to content', back: 'Back', email: 'Email address', yes: 'Yes', no: 'No', open: 'Open', unavailable: 'Currently unavailable', results: '{count} results', noResults: 'No results', optional: 'Optional', menuClose: 'Close menu', accountMenu: 'Account menu', breadcrumbs: 'Breadcrumbs', status: 'Status', free: 'Free', price: 'Price', duration: 'Duration', access: 'Access period', days: '{count} days', minutes: '{count} minutes', hours: '{count} hours', lifetime: 'Lifetime access', course: 'Course', courses: 'Courses', package: 'Package', details: 'Details', viewDetails: 'View details', comingSoon: 'This step will be available in the checkout phase.',
    },
    auth: {
        or: 'or', google: 'Continue with Google', googleUnavailable: 'Google sign-in is unavailable. Check the domain and callback configuration.', googleAccount: 'Google sign-in is not available for this account. Use your existing sign-in method or contact support.', googleFailed: 'Google sign-in could not be completed. Please try again.',
        title: 'Welcome back', subtitle: 'Enter your learning space and continue from where you left off.', email: 'Email address', password: 'Password', remember: 'Remember me', invalid: 'Unable to sign in. Check your details and try again.', submit: 'Sign in to my account', secure: 'Secure session-based access', emailRequired: 'Email is required.', emailInvalid: 'Enter a valid email address.', passwordRequired: 'Password is required.', registrationUnavailable: 'Online registration is not currently available. Contact the academy to join.', noReset: 'Password recovery is not currently available through the platform.',
        registerTitle: 'Create a learner account', registerSubtitle: 'Start your learning journey with your own account.', registerLink: 'Create an account', name: 'Full name', confirmPassword: 'Confirm password', registerSubmit: 'Create account', registerSuccess: 'Your account is ready. You can sign in now.', alreadyHaveAccount: 'Already have an account? Sign in', forgotLink: 'Forgot password?', forgotTitle: 'Reset your password', forgotSubtitle: 'Enter your email and we will send a reset link if the account exists.', forgotSubmit: 'Send reset link', forgotSuccess: 'If the account exists, a reset link will be sent to your email.', resetTitle: 'Set a new password', resetSubtitle: 'Choose a new password for your account.', resetSubmit: 'Change password', resetSuccess: 'Your password has changed. Sign in with the new one.', resetInvalid: 'The link is invalid or expired. Request a new one.', requestAgain: 'Request a new link', nameRequired: 'Name is required.', confirmRequired: 'Password confirmation is required.', passwordMismatch: 'Passwords do not match.',
    },
    nav: { primary: 'Primary navigation', mobile: 'Mobile navigation', overview: 'Overview', courses: 'Courses', packages: 'Packages & paths', howItWorks: 'How it works', learning: 'My learning', content: 'Content management', website: 'Website & policies', users: 'Users', assignments: 'Assignments', tickets: 'Support tickets', orders: 'Orders', main: 'Main navigation' },
    home: {
        eyebrow: 'Skills today for a brighter tomorrow', heroTitle: 'Professional learning designed to move you from knowledge to achievement', heroDescription: 'Discover focused courses and learning paths with clear curricula and an experience shaped around your professional ambition.', browseCourses: 'Explore courses', browsePackages: 'Explore learning paths', recentEyebrow: 'Learn with focus', recentTitle: 'Latest available courses', recentDescription: 'Content currently published by the academy, ordered from newest so you can start with the right choice.', categoriesEyebrow: 'Choose your field', categoriesTitle: 'Learning fields that move you closer to your goal', categoriesDescription: 'Browse available categories and go directly to published courses in your field.', packagesEyebrow: 'A complete journey', packagesTitle: 'Packages and paths that connect the knowledge', packagesDescription: 'Related courses brought together in one clear learning experience.', howEyebrow: 'Simple steps', howTitle: 'Your learning journey starts with one decision', howDescription: 'A clear path from discovery to practical application.', stepExplore: 'Explore your options', stepExploreText: 'Compare published courses and packages based on your goal and level.', stepLearn: 'Learn at your pace', stepLearnText: 'Follow an organized curriculum with clear details before you begin.', stepGrow: 'Build your skill', stepGrowText: 'Turn knowledge into professional progress through practical steps.', whyEyebrow: 'Why JCEC', whyTitle: 'An experience focused on what you actually need', whyPractical: 'Career focused', whyPracticalText: 'Programs designed around skills that apply in a professional environment.', whyClear: 'Clear experience', whyClearText: 'Transparent curriculum, duration, and level details before you decide.', whyFlexible: 'Flexible learning', whyFlexibleText: 'Access content for the period defined for each course or package.', ctaTitle: 'Ready for your next step?', ctaText: 'Browse published content and choose the experience closest to your ambition.', emptyCourses: 'No courses are currently published.', emptyPackages: 'No packages are currently published.', emptyCategories: 'No categories are currently available.',
    },
    catalog: {
        coursesTitle: 'Courses that create real progress', coursesDescription: 'Search and filter using options supported by the academy catalog.', packagesTitle: 'Packages and learning paths', packagesDescription: 'Discover published course collections and choose the journey that matches your goal.', searchCourses: 'Search course title or description', searchPackages: 'Search package title or description', category: 'Category', allCategories: 'All categories', level: 'Level', allLevels: 'All levels', language: 'Content language', allLanguages: 'All languages', type: 'Package type', allTypes: 'All types', sort: 'Sort by', latest: 'Newest', oldest: 'Oldest', priceAsc: 'Price: low to high', priceDesc: 'Price: high to low', titleSort: 'Title A–Z', price: 'Price', packagePrice: 'Package price', free: 'Free', featured: 'Featured', minutes: '{count} min', courseCount: '{count} courses', ratingLabel: 'Rated {rating} out of 5 from {count} reviews', filters: 'Filter results', filtersDescription: 'Your choices stay in the URL so you can share them.', emptyCourses: 'No matching courses found', emptyCoursesText: 'Try a different search term or remove some filters.', emptyPackages: 'No matching packages found', emptyPackagesText: 'Try changing the search or package type.', loadError: 'Content could not be loaded right now.', resultSummary: 'Showing {from}–{to} of {total} results',
    },
    course: {
        overview: 'Overview', curriculum: 'Course curriculum', outcomes: 'What you will learn', requirements: 'Requirements', audience: 'Who this course is for', tools: 'Required tools', instructor: 'Course instructor', reviews: 'Learner reviews', reviewCount: '{count} published reviews', noReviews: 'No published reviews yet.', lessons: '{count} lessons', preview: 'Preview available', lesson: 'Lesson', certificate: 'Completion certificate', discussions: 'Course discussions', accessDays: '{count} days of access', accessUnspecified: 'Access period not specified', signInCta: 'Sign in to continue', purchaseSoon: 'Purchase coming soon', published: 'Published course', detailError: 'Course details could not be loaded.', notFound: 'The requested course was not found.', backToCourses: 'Back to courses', ratingDistribution: 'Rating distribution',
    },
    packages: {
        ...adminContent.packages,
        included: 'Included courses', overview: 'About this package', required: 'Required', optional: 'Optional', sequential: 'Sequential learning path', flexible: 'Flexible package', lifetime: 'Lifetime package access', accessDays: 'Package access for {count} days', signInCta: 'Sign in to continue', purchaseSoon: 'Package purchase coming soon', detailError: 'Package details could not be loaded.', notFound: 'The requested package was not found.', backToPackages: 'Back to packages', noCourses: 'No published courses are currently included in this package.', courseAccessNote: 'The displayed access period belongs to the package; individual course access details may differ.',
    },
    labels: {
        levels: { beginner: 'Beginner', intermediate: 'Intermediate', advanced: 'Advanced', all_levels: 'All levels' }, languages: { ar: 'Arabic', en: 'English' }, packageTypes: { package: 'Course package', learning_path: 'Learning path' }, lessonTypes: { video: 'Video', text: 'Text lesson', file: 'File', link: 'Link' }, roles: { student: 'Student', instructor: 'Instructor', admin: 'Administrator', content_manager: 'Content manager', sales_support: 'Sales & support' }, statuses: { active: 'Active', inactive: 'Inactive', blocked: 'Blocked' },
    },
    footer: { explore: 'Explore the platform', learning: 'Learn with confidence', learningText: 'We show you the content, level, and duration before you begin so you can make a clear decision.', rights: 'All rights reserved.' },
    policies: { privacy: 'Privacy policy', terms: 'Terms of use', refund: 'Refund policy', description: 'The academy’s official policies and notices.', notPublished: 'Approved policy text has not been published. This is not an effective legal policy.', version: 'Version', manage: 'Manage policies', manageDescription: 'Save drafts, then publish text approved by the appropriate owner.', legalApproval: 'Do not publish copy before legal approval by the academy. Drafts are not public.', arabicDraft: 'Arabic draft', englishDraft: 'English draft', published: 'Published', saved: 'Changes saved.', publish: 'Publish approved copy', publishConfirm: 'Confirm that the Arabic and English texts are approved for publication?', publicPreview: 'View public page' },
    dashboard: { greeting: 'Welcome, {name}', subtitle: 'Everything you need to begin your day at JCEC Academy in one place.', account: 'Account details', roles: 'Roles', permissions: 'Effective permissions', permissionCount: '{count} active permissions', next: 'Upcoming modules will appear here as they are implemented.', publicCatalog: 'Browse the public catalog', publicCatalogText: 'Review the visitor experience and currently published courses and packages.', workspace: 'Your workspace', email: 'Email address', profileStatus: 'Account status' },
    errors: { forbiddenTitle: 'Access denied', forbiddenText: 'This page requires additional permissions.', notFoundTitle: 'Page not found', notFoundText: 'The address may be incorrect or the page has moved.', startupTitle: 'Unable to start the app', startupText: 'We could not verify your session. Please try again.', network: 'Unable to reach the server. Check your connection and try again.', server: 'An unexpected server error occurred.', generic: 'The request could not be completed.' },
    pages: { student: 'Student area', admin: 'Administration', instructor: 'Instructor area', support: 'Sales & support' },
};
