export const en = {
    myCourses: 'My Courses', description: 'Your learning space. Access and progress are confirmed by the academy.', empty: 'No courses yet', emptyDescription: 'Your enrolled courses will appear here.', continue: 'Continue learning', resume: 'Resume: {lesson}', instructor: 'Instructor', enrollment: 'Enrollment', expires: 'Access ends: {date}', lifetime: 'Lifetime access',
    access: { active: 'Active access', locked: 'Owned, locked', expired: 'Access expired', suspended: 'Enrollment suspended', scheduled: 'Access not started', revoked: 'Access revoked', unavailable: 'No current access' },
    status: { active: 'Active enrollment', completed: 'Completed enrollment', suspended: 'Suspended enrollment' },
    progress: 'Course progress', counts: '{completed} of {total} lessons complete', curriculum: 'Course curriculum', showCurriculum: 'Show curriculum', hideCurriculum: 'Hide curriculum', noLessons: 'No published lessons yet', noLessonsDescription: 'The academy has not published lessons for this course yet.',
    lessonStatus: { not_started: 'Not started', in_progress: 'In progress', completed: 'Completed' },
    types: { video: 'Video', text: 'Reading', file: 'Learning files', link: 'External link' },
    complete: 'Mark lesson complete', completed: 'Lesson complete', saving: 'Saving…', saved: 'Progress saved', savePosition: 'Save video position', videoAuthorizing: 'Authorizing protected playback…', videoRetry: 'Refresh video access', videoUnavailable: 'No playable video URL is available. Contact the academy for this lesson.', videoFailed: 'This video could not be played. Your saved progress is unchanged.', textEmpty: 'No reading content is available.', openLink: 'Open lesson link', unsafeLink: 'No safe lesson link is available.', fileDescription: 'Use the protected resources below to download this lesson’s learning files.',
    resources: 'Lesson resources', noResources: 'No resources for this lesson', download: 'Download', downloading: 'Downloading…', openResource: 'Open reference', resourceUnavailable: 'Resource unavailable', previousLesson: 'Previous lesson', nextLesson: 'Next lesson', back: 'Back to My Courses',
    unauthenticated: 'Your session has ended. Sign in again to continue.', forbidden: 'You no longer have access to this course. It may have expired, been revoked, or your enrollment may be suspended.', notFound: 'The course, lesson or resource is no longer available.', requestFailed: 'Unable to load or save learning data. Please try again.', invalidProgress: 'The video position could not be saved. Check the lesson duration and try again.', rateLimited: 'Too many requests. Please wait before trying again.', downloadFailed: 'The resource could not be downloaded. Please try again.',
};

export const ar = {
    myCourses: 'دوراتي', description: 'مساحة تعلّمك. صلاحيات الوصول والتقدّم معتمدة من الأكاديمية.', empty: 'لا توجد دورات بعد', emptyDescription: 'ستظهر هنا الدورات المسجّل بها.', continue: 'متابعة التعلّم', resume: 'متابعة: {lesson}', instructor: 'المدرّب', enrollment: 'التسجيل', expires: 'ينتهي الوصول: {date}', lifetime: 'وصول دائم',
    access: { active: 'وصول فعّال', locked: 'مملوكة، مقفلة', expired: 'انتهى الوصول', suspended: 'التسجيل معلّق', scheduled: 'لم يبدأ الوصول', revoked: 'الوصول ملغى', unavailable: 'لا يوجد وصول حالي' },
    status: { active: 'تسجيل فعّال', completed: 'تسجيل مكتمل', suspended: 'تسجيل معلّق' },
    progress: 'تقدّم الدورة', counts: 'اكتمل {completed} من {total} درسًا', curriculum: 'محتوى الدورة', showCurriculum: 'عرض محتوى الدورة', hideCurriculum: 'إخفاء محتوى الدورة', noLessons: 'لا توجد دروس منشورة بعد', noLessonsDescription: 'لم تنشر الأكاديمية دروس هذه الدورة بعد.',
    lessonStatus: { not_started: 'لم يبدأ', in_progress: 'قيد التعلّم', completed: 'مكتمل' },
    types: { video: 'فيديو', text: 'قراءة', file: 'ملفات التعلّم', link: 'رابط خارجي' },
    complete: 'تحديد الدرس كمكتمل', completed: 'الدرس مكتمل', saving: 'جارٍ الحفظ…', saved: 'تم حفظ التقدّم', savePosition: 'حفظ موضع الفيديو', videoAuthorizing: 'جارٍ تفويض تشغيل الفيديو المحمي…', videoRetry: 'تجديد وصول الفيديو', videoUnavailable: 'لا يوجد رابط فيديو قابل للتشغيل. تواصل مع الأكاديمية بخصوص هذا الدرس.', videoFailed: 'تعذّر تشغيل الفيديو. لم يتغيّر تقدّمك المحفوظ.', textEmpty: 'لا يوجد محتوى للقراءة.', openLink: 'فتح رابط الدرس', unsafeLink: 'لا يوجد رابط آمن للدرس.', fileDescription: 'نزّل ملفات التعلّم من المرفقات المحمية أدناه.',
    resources: 'مرفقات الدرس', noResources: 'لا توجد مرفقات لهذا الدرس', download: 'تنزيل', downloading: 'جارٍ التنزيل…', openResource: 'فتح المرجع', resourceUnavailable: 'المرفق غير متاح', previousLesson: 'الدرس السابق', nextLesson: 'الدرس التالي', back: 'العودة إلى دوراتي',
    unauthenticated: 'انتهت جلستك. سجّل الدخول مجددًا للمتابعة.', forbidden: 'لم يعد لديك وصول لهذه الدورة. قد تكون المدة انتهت أو أُلغي الوصول أو عُلّق التسجيل.', notFound: 'الدورة أو الدرس أو المرفق لم يعد متاحًا.', requestFailed: 'تعذّر تحميل بيانات التعلّم أو حفظها. حاول مجددًا.', invalidProgress: 'تعذّر حفظ موضع الفيديو. تحقّق من مدة الدرس وحاول مجددًا.', rateLimited: 'طلبات كثيرة. انتظر قليلًا قبل المحاولة.', downloadFailed: 'تعذّر تنزيل المرفق. حاول مجددًا.',
};
