export const ar = {
    discovery: {
        instructors: 'المدربون', instructorProfile: 'ملف المدرب', publishedCourses: 'الدورات المنشورة', noInstructors: 'لا توجد ملفات مدربين منشورة حاليًا.', jobTitle: 'المسمى المهني', experience: 'سنوات الخبرة', years: '{count} سنوات', specialties: 'التخصصات', biography: 'نبذة عن المدرب', viewProfile: 'الملف الشخصي', language: 'لغة الدورة', trainingType: 'نوع التدريب', allTrainingTypes: 'جميع أنواع التدريب', allInstructors: 'جميع المدربين', priceType: 'السعر', allPrices: 'مجاني ومدفوع', paid: 'مدفوع', rating: 'الحد الأدنى للتقييم', allRatings: 'كل التقييمات', ratingAtLeast: 'تقييم {count}/5 فأكثر', highestRated: 'الأعلى تقييمًا', bestseller: 'الأكثر مبيعًا', courseFaq: 'أسئلة الدورة الشائعة', relatedCourses: 'دورات ذات صلة', includedPackages: 'باقات تتضمن هذه الدورة', promo: 'فيديو تعريفي', preview: 'شاهد المعاينة', previewUnavailable: 'هذه المعاينة غير متاحة.', previewLink: 'فتح رابط المعاينة', savings: 'توفير حقيقي مقارنة بشراء الدورات منفردة', featuredInstructors: 'تعرّف على المدربين', learnerReviews: 'آراء متدربين معتمدة', noReviews: 'لا توجد آراء منشورة حاليًا.',
        trainingTypes: { recorded: 'مسجل', live: 'مباشر', hybrid: 'هجين' },
    },
    site: {
        about: 'عن الأكاديمية', faq: 'الأسئلة الشائعة', contact: 'تواصل معنا', intro: 'معلومات الأكاديمية المنشورة رسميًا.', notPublished: 'المحتوى التحريري المعتمد لم يُنشر بعد.', noFaq: 'لا توجد أسئلة منشورة حاليًا.', contactIntro: 'أرسل استفسارك وسيتولى الفريق مراجعته.', subject: 'الموضوع', message: 'الرسالة', send: 'إرسال الرسالة', sent: 'استلمنا رسالتك.', manage: 'إدارة محتوى الموقع', manageIntro: 'أدخل النصوص الرسمية بالعربية والإنجليزية وانشرها بعد الاعتماد.', arabic: 'النص العربي', english: 'النص الإنجليزي', save: 'حفظ المسودة', publish: 'نشر المحتوى', published: 'منشور', draft: 'غير منشور', questionAr: 'السؤال بالعربية', answerAr: 'الإجابة بالعربية', questionEn: 'السؤال بالإنجليزية', answerEn: 'الإجابة بالإنجليزية', active: 'منشور', order: 'الترتيب', addFaq: 'إضافة سؤال', saveFaq: 'حفظ السؤال', removeFaq: 'حذف السؤال', contacts: 'رسائل التواصل', editorialRequired: 'المحتوى التحريري مطلوب من الأكاديمية.',
    },
    profile: {
        title: 'ملفي الشخصي', description: 'حدّث بيانات التواصل والتخصص الخاصة بك.', name: 'الاسم الكامل', email: 'البريد الإلكتروني', phone: 'الهاتف', country: 'الدولة', selectCountry: 'اختر الدولة', city: 'المدينة', specialization: 'التخصص', save: 'حفظ التغييرات', saved: 'تم تحديث الملف الشخصي.', avatar: 'الصورة الشخصية', upload: 'اختر صورة شخصية', remove: 'إزالة الصورة', avatarHint: 'JPG أو PNG أو WebP، حتى 2 ميغابايت. اضغط على الصورة لتغييرها.', password: 'تغيير كلمة المرور', currentPassword: 'كلمة المرور الحالية', newPassword: 'كلمة المرور الجديدة', confirmPassword: 'تأكيد كلمة المرور الجديدة', changePassword: 'تغيير كلمة المرور', passwordChanged: 'تغيرت كلمة المرور. ستنتهي الجلسات الأخرى.', language: 'لغة الحساب', languageHint: 'تُستخدم في الواجهة والرسائل المستقبلية.', error: 'تعذر حفظ التغييرات. راجع الحقول وحاول مجددًا.',
    },
};

export const en = {
    discovery: {
        instructors: 'Instructors', instructorProfile: 'Instructor profile', publishedCourses: 'Published courses', noInstructors: 'No instructor profiles are published yet.', jobTitle: 'Professional title', experience: 'Years of experience', years: '{count} years', specialties: 'Specialties', biography: 'About the instructor', viewProfile: 'View profile', language: 'Course language', trainingType: 'Training type', allTrainingTypes: 'All training types', allInstructors: 'All instructors', priceType: 'Price', allPrices: 'Free and paid', paid: 'Paid', rating: 'Minimum rating', allRatings: 'All ratings', ratingAtLeast: '{count} stars and up', highestRated: 'Highest rated', bestseller: 'Bestselling', courseFaq: 'Course FAQs', relatedCourses: 'Related courses', includedPackages: 'Packages including this course', promo: 'Promotional video', preview: 'Watch preview', previewUnavailable: 'This preview is unavailable.', previewLink: 'Open preview link', savings: 'Actual savings versus individual courses', featuredInstructors: 'Meet the instructors', learnerReviews: 'Approved learner reviews', noReviews: 'No published reviews yet.',
        trainingTypes: { recorded: 'Recorded', live: 'Live', hybrid: 'Hybrid' },
    },
    site: {
        about: 'About the academy', faq: 'Frequently asked questions', contact: 'Contact us', intro: 'Officially published academy information.', notPublished: 'Approved editorial content has not been published yet.', noFaq: 'No questions are published yet.', contactIntro: 'Send your inquiry for the team to review.', subject: 'Subject', message: 'Message', send: 'Send message', sent: 'Your message has been received.', manage: 'Manage site content', manageIntro: 'Enter official Arabic and English copy and publish after approval.', arabic: 'Arabic text', english: 'English text', save: 'Save draft', publish: 'Publish content', published: 'Published', draft: 'Not published', questionAr: 'Arabic question', answerAr: 'Arabic answer', questionEn: 'English question', answerEn: 'English answer', active: 'Published', order: 'Order', addFaq: 'Add question', saveFaq: 'Save question', removeFaq: 'Remove question', contacts: 'Contact messages', editorialRequired: 'Editorial copy is required from the academy.',
    },
    profile: {
        title: 'My profile', description: 'Update your contact and specialty information.', name: 'Full name', email: 'Email address', phone: 'Phone', country: 'Country', selectCountry: 'Select a country', city: 'City', specialization: 'Specialization', save: 'Save changes', saved: 'Profile updated.', avatar: 'Profile image', upload: 'Choose profile image', remove: 'Remove image', avatarHint: 'JPG, PNG or WebP, up to 2 MB. Click the image to change it.', password: 'Change password', currentPassword: 'Current password', newPassword: 'New password', confirmPassword: 'Confirm new password', changePassword: 'Change password', passwordChanged: 'Password changed. Other sessions will end.', language: 'Account language', languageHint: 'Used for the interface and future messages.', error: 'Could not save changes. Review the fields and retry.',
    },
};
