export const en = {
    reviews: {
        heading: 'Your course review', description: 'Share your experience with this course.', write: 'Write a review', edit: 'Edit review', save: 'Submit review', rating: 'Rating', ratingOption: '{count} out of 5 stars', title: 'Title (optional)', body: 'Your review (optional)', selectRating: 'Choose a rating from 1 to 5.', titleLong: 'The title must be 255 characters or fewer.', bodyLong: 'The review must be 10,000 characters or fewer.', status: { pending: 'Pending approval', published: 'Published', rejected: 'Rejected', hidden: 'Hidden' }, pendingNote: 'Your review is awaiting approval and is not public yet.', publishedNote: 'This review is currently public. Editing sends it back for approval and removes it from public reviews and ratings until approved again.', rejectedNote: 'This review was not approved. You can edit and resubmit while you have course access.', hiddenNote: 'This review is not public. You can edit and resubmit while you have course access.', reason: 'Moderation note', noAccess: 'Your review remains visible to you, but editing requires active course access and an unsuspended enrollment.', ineligible: 'An active course enrollment and access are required to review this course.', unavailable: 'Unable to load your review.', saveFailed: 'Unable to submit your review. Check your access and try again.', pendingSuccess: 'Your review was submitted for approval.',
    },
    support: {
        heading: 'Support', description: 'Ask the academy for help and follow your requests.', newTicket: 'New ticket', ticket: 'Ticket', number: 'Ticket number', subject: 'Subject', category: 'Category', priority: 'Priority', statusLabel: 'Status', lastReply: 'Last reply', created: 'Created', openTicket: 'View conversation', empty: 'No support tickets yet.', emptyDescription: 'Create a ticket whenever you need help.', listError: 'Unable to load your tickets.', detailError: 'Unable to load this ticket.', createHeading: 'Create a support ticket', createDescription: 'Describe your question clearly so we can help.', message: 'Message', relatedCourse: 'Related course (optional)', relatedOrder: 'Related order (optional)', noRelated: 'None', loadMore: 'Load more options', relatedLoadError: 'Some related options could not be loaded. You can still send the ticket without them.', files: 'Attachments (optional)', fileHint: 'Up to 5 files, 10 MB each: PDF, images, TXT, DOC or DOCX.', tooManyFiles: 'Choose no more than 5 attachments.', invalidFile: 'A file type or size is not allowed (maximum 10 MB per file).', subjectRequired: 'Enter a subject (maximum 255 characters).', categoryRequired: 'Choose a category.', bodyRequired: 'Enter a message (maximum 10,000 characters).', sendTicket: 'Send ticket', createFailed: 'Unable to create the ticket. Check your entries and try again.', conversation: 'Conversation', noMessages: 'No visible messages yet.', reply: 'Your reply', sendReply: 'Send reply', replyFailed: 'Unable to send your reply.', closedNote: 'This ticket is closed. Reopen it before replying.', reopen: 'Reopen ticket', reopenFailed: 'Unable to reopen this ticket.', resolvedNote: 'Replying to a resolved ticket will reopen it.', waitingNote: 'Your reply will move this ticket back to in progress.', downloadFailed: 'Unable to download this attachment.', download: 'Download', you: 'You', staff: 'Academy team', status: { open: 'Open', in_progress: 'In progress', waiting_for_student: 'Waiting for you', resolved: 'Resolved', closed: 'Closed' }, categories: { general: 'General', technical: 'Technical', course_content: 'Course content', payment: 'Payment', enrollment: 'Enrollment', certificate: 'Certificate', other: 'Other' }, priorities: { low: 'Low', normal: 'Normal', high: 'High', urgent: 'Urgent' },
    },
};

export const ar = {
    reviews: {
        heading: 'مراجعتك للدورة', description: 'شارك تجربتك مع هذه الدورة.', write: 'اكتب مراجعة', edit: 'تعديل المراجعة', save: 'إرسال المراجعة', rating: 'التقييم', ratingOption: '{count} من 5 نجوم', title: 'العنوان (اختياري)', body: 'مراجعتك (اختيارية)', selectRating: 'اختر تقييمًا من 1 إلى 5.', titleLong: 'يجب ألا يتجاوز العنوان 255 حرفًا.', bodyLong: 'يجب ألا تتجاوز المراجعة 10,000 حرف.', status: { pending: 'بانتظار الاعتماد', published: 'منشورة', rejected: 'مرفوضة', hidden: 'مخفية' }, pendingNote: 'مراجعتك تنتظر الاعتماد ولا تظهر للعموم الآن.', publishedNote: 'هذه المراجعة منشورة حاليًا. تعديلها يعيدها للاعتماد ويزيلها من المراجعات والتقييمات العامة حتى تُعتمد مجددًا.', rejectedNote: 'لم تُعتمد هذه المراجعة. يمكنك تعديلها وإعادة إرسالها ما دام وصولك للدورة فعّالًا.', hiddenNote: 'هذه المراجعة غير ظاهرة للعموم. يمكنك تعديلها وإعادة إرسالها ما دام وصولك للدورة فعّالًا.', reason: 'ملاحظة الإشراف', noAccess: 'تبقى مراجعتك ظاهرة لك، لكن تعديلها يتطلب وصولًا فعّالًا وتسجيلًا غير معلّق بالدورة.', ineligible: 'يلزم تسجيل ووصول فعّالان للدورة لكتابة مراجعة.', unavailable: 'تعذر تحميل مراجعتك.', saveFailed: 'تعذر إرسال المراجعة. تحقق من صلاحية الوصول وحاول مجددًا.', pendingSuccess: 'أُرسلت مراجعتك للاعتماد.',
    },
    support: {
        heading: 'الدعم', description: 'تواصل مع الأكاديمية وتابع طلباتك.', newTicket: 'تذكرة جديدة', ticket: 'تذكرة', number: 'رقم التذكرة', subject: 'الموضوع', category: 'التصنيف', priority: 'الأولوية', statusLabel: 'الحالة', lastReply: 'آخر رد', created: 'تاريخ الإنشاء', openTicket: 'عرض المحادثة', empty: 'لا توجد تذاكر دعم بعد.', emptyDescription: 'أنشئ تذكرة عندما تحتاج إلى مساعدة.', listError: 'تعذر تحميل تذاكرك.', detailError: 'تعذر تحميل التذكرة.', createHeading: 'إنشاء تذكرة دعم', createDescription: 'اشرح استفسارك بوضوح حتى نتمكن من مساعدتك.', message: 'الرسالة', relatedCourse: 'الدورة ذات الصلة (اختياري)', relatedOrder: 'الطلب ذو الصلة (اختياري)', noRelated: 'لا يوجد', loadMore: 'تحميل خيارات إضافية', relatedLoadError: 'تعذر تحميل بعض الخيارات ذات الصلة. يمكنك إرسال التذكرة دونها.', files: 'المرفقات (اختياري)', fileHint: 'حتى 5 ملفات، 10 ميغابايت لكل ملف: PDF، صور، TXT، DOC أو DOCX.', tooManyFiles: 'اختر خمسة مرفقات كحد أقصى.', invalidFile: 'نوع أحد الملفات أو حجمه غير مسموح (10 ميغابايت كحد أقصى لكل ملف).', subjectRequired: 'أدخل الموضوع (255 حرفًا كحد أقصى).', categoryRequired: 'اختر تصنيفًا.', bodyRequired: 'أدخل الرسالة (10,000 حرف كحد أقصى).', sendTicket: 'إرسال التذكرة', createFailed: 'تعذر إنشاء التذكرة. راجع البيانات وحاول مجددًا.', conversation: 'المحادثة', noMessages: 'لا توجد رسائل ظاهرة بعد.', reply: 'ردك', sendReply: 'إرسال الرد', replyFailed: 'تعذر إرسال الرد.', closedNote: 'هذه التذكرة مغلقة. أعد فتحها قبل الرد.', reopen: 'إعادة فتح التذكرة', reopenFailed: 'تعذرت إعادة فتح التذكرة.', resolvedNote: 'سيؤدي الرد على التذكرة المحلولة إلى إعادة فتحها.', waitingNote: 'سينقل ردك التذكرة إلى قيد المعالجة.', downloadFailed: 'تعذر تنزيل هذا المرفق.', download: 'تنزيل', you: 'أنت', staff: 'فريق الأكاديمية', status: { open: 'مفتوحة', in_progress: 'قيد المعالجة', waiting_for_student: 'بانتظار ردك', resolved: 'محلولة', closed: 'مغلقة' }, categories: { general: 'عام', technical: 'تقني', course_content: 'محتوى الدورة', payment: 'الدفع', enrollment: 'التسجيل', certificate: 'الشهادات', other: 'أخرى' }, priorities: { low: 'منخفضة', normal: 'عادية', high: 'مرتفعة', urgent: 'عاجلة' },
    },
};
