<script setup>
import { onMounted, ref } from 'vue'; import { useRoute } from 'vue-router'; import { useI18n } from 'vue-i18n'; import { useAuthStore } from '../stores/auth';
import { fetchModerationReview, publishModerationReview, rejectModerationReview, hideModerationReview } from '../api/admin-operations'; import { formatDate } from '../utils/catalog';
import PageHeading from '../components/ui/PageHeading.vue'; import BaseAlert from '../components/ui/BaseAlert.vue'; import BaseButton from '../components/ui/BaseButton.vue'; import LoadingState from '../components/ui/LoadingState.vue'; import OperationStatusBadge from '../components/admin/OperationStatusBadge.vue'; import OperationReasonDialog from '../components/admin/OperationReasonDialog.vue';
const route = useRoute(); const auth = useAuthStore(); const { t, locale } = useI18n(); const item = ref(null); const loading = ref(true); const busy = ref(false); const error = ref(null); const action = ref(null);
async function load() { loading.value = true; error.value = null; try { item.value = await fetchModerationReview(route.params.id); } catch (failure) { error.value = failure; } finally { loading.value = false; } }
onMounted(load);
async function publish() { if (busy.value || !['pending', 'hidden'].includes(item.value?.status) || !window.confirm(t('operations.publishConfirm'))) return; busy.value = true; error.value = null; try { await publishModerationReview(item.value.id); item.value = await fetchModerationReview(item.value.id); } catch (failure) { error.value = failure; await fetchModerationReview(route.params.id).then((fresh) => { item.value = fresh; }).catch(() => {}); } finally { busy.value = false; } }
async function act(reason) { if (busy.value || !['reject', 'hide'].includes(action.value)) return; busy.value = true; error.value = null; try { if (action.value === 'reject') await rejectModerationReview(item.value.id, reason); else await hideModerationReview(item.value.id, reason); action.value = null; item.value = await fetchModerationReview(item.value.id); } catch (failure) { error.value = failure; await fetchModerationReview(route.params.id).then((fresh) => { item.value = fresh; }).catch(() => {}); } finally { busy.value = false; } }
</script>
<template><div class="mx-auto max-w-4xl space-y-6" :dir="locale === 'ar' ? 'rtl' : 'ltr'"><RouterLink :to="{ name: 'admin.reviews.index' }" class="font-bold text-brand">{{ t('operations.back') }}</RouterLink><LoadingState v-if="loading" /><BaseAlert v-else-if="error && !item" tone="danger">{{ t('operations.loadError') }}</BaseAlert><template v-else-if="item"><PageHeading :title="item.course?.title ?? t('operations.reviews')" /><BaseAlert v-if="error" tone="danger">{{ t('operations.saveError') }} {{ error?.errors?.status?.[0] ?? '' }}</BaseAlert><section class="space-y-4 rounded-3xl border bg-white p-6"><div class="flex flex-wrap items-center justify-between gap-3"><OperationStatusBadge group="reviewStatus" :status="item.status" /><span class="text-sm text-slate-500">{{ formatDate(item.submitted_at, locale) }}</span></div><p class="font-bold">{{ item.reviewer?.name }} · {{ item.rating }}/5</p><h2 class="text-lg font-black">{{ item.title }}</h2><p class="whitespace-pre-wrap break-words leading-7">{{ item.body }}</p></section><div v-if="auth.can('reviews.moderate')" class="flex flex-wrap gap-3"><BaseButton v-if="['pending', 'hidden'].includes(item.status)" :loading="busy" @click="publish">{{ t('operations.publish') }}</BaseButton><BaseButton v-if="item.status === 'pending'" variant="secondary" :disabled="busy" @click="action = 'reject'">{{ t('operations.reject') }}</BaseButton><BaseButton v-if="item.status === 'published'" variant="secondary" :disabled="busy" @click="action = 'hide'">{{ t('operations.hide') }}</BaseButton></div><section v-if="item.history?.length" class="space-y-3 rounded-3xl border bg-white p-6"><h2 class="font-black">{{ t('operations.history') }}</h2><ol class="space-y-2"><li v-for="entry in item.history" :key="entry.id" class="border-s ps-4 text-sm"><strong>{{ entry.actor_name }} · {{ entry.action }}</strong><p>{{ formatDate(entry.created_at, locale) }} · {{ entry.from_status }} → {{ entry.to_status }}</p><p v-if="entry.reason">{{ entry.reason }}</p></li></ol></section><OperationReasonDialog :open="Boolean(action)" :title="t(action === 'reject' ? 'operations.rejectReview' : 'operations.hideReview')" :busy="busy" :error="error" @confirm="act" @cancel="action = null" /></template></div></template>
