<script setup>
import { reactive, ref, watch } from 'vue'; import { useRoute, useRouter } from 'vue-router'; import { useI18n } from 'vue-i18n';
import { fetchOperationalCertificates } from '../api/admin-operations'; import { formatDate } from '../utils/catalog';
import PageHeading from '../components/ui/PageHeading.vue'; import BaseAlert from '../components/ui/BaseAlert.vue'; import LoadingState from '../components/ui/LoadingState.vue'; import EmptyState from '../components/ui/EmptyState.vue'; import PaginationNav from '../components/ui/PaginationNav.vue'; import OperationStatusBadge from '../components/admin/OperationStatusBadge.vue';
const route = useRoute(); const router = useRouter(); const { t, locale } = useI18n(); const filters = reactive({ status: '', course_id: '', user_id: '' }); const items = ref([]); const meta = ref(null); const loading = ref(true); const error = ref(null); let sequence = 0;
async function load() { const current = ++sequence; loading.value = true; error.value = null; Object.keys(filters).forEach((key) => { filters[key] = String(route.query[key] ?? ''); }); try { const result = await fetchOperationalCertificates({ page: Number(route.query.page) || 1, ...Object.fromEntries(Object.entries(filters).filter(([, value]) => value)) }); if (current === sequence) { items.value = result.items; meta.value = result.meta; } } catch (failure) { if (current === sequence) error.value = failure; } finally { if (current === sequence) loading.value = false; } }
watch(() => route.query, load, { immediate: true, deep: true });
function apply() { router.push({ name: 'admin.certificates.index', query: Object.fromEntries(Object.entries(filters).filter(([, value]) => value)) }); }
function page(value) { router.push({ name: 'admin.certificates.index', query: { ...route.query, page: value } }); }
</script>
<template><div class="space-y-6" :dir="locale === 'ar' ? 'rtl' : 'ltr'"><PageHeading :title="t('operations.certificates')" /><form class="flex flex-wrap gap-3 rounded-3xl border bg-white p-4" @submit.prevent="apply"><label class="sr-only" for="certificate-status">{{ t('operations.status') }}</label><select id="certificate-status" v-model="filters.status" class="min-h-11 rounded-xl border px-4"><option value="">{{ t('operations.all') }}</option><option value="issued">{{ t('operations.certificateStatus.issued') }}</option><option value="revoked">{{ t('operations.certificateStatus.revoked') }}</option></select><label class="sr-only" for="certificate-course">{{ t('operations.course') }}</label><input id="certificate-course" v-model="filters.course_id" type="number" min="1" :placeholder="t('operations.course')" class="min-h-11 rounded-xl border px-4"><label class="sr-only" for="certificate-student">{{ t('operations.student') }}</label><input id="certificate-student" v-model="filters.user_id" type="number" min="1" :placeholder="t('operations.student')" class="min-h-11 rounded-xl border px-4"><button type="submit" class="min-h-11 rounded-xl bg-brand px-5 font-bold text-white">{{ t('operations.filter') }}</button></form><LoadingState v-if="loading" /><BaseAlert v-else-if="error" tone="danger">{{ t('operations.loadError') }}</BaseAlert><EmptyState v-else-if="!items.length" :title="t('operations.empty')" /><div v-else class="grid gap-3"><RouterLink v-for="certificate in items" :key="certificate.id" :to="{ name: 'admin.certificates.show', params: { id: certificate.id } }" class="flex flex-wrap items-center justify-between gap-3 rounded-2xl border bg-white p-5 hover:border-brand"><div><p class="font-black">{{ certificate.certificate_number }}</p><p class="text-sm">{{ certificate.student_name }} · {{ certificate.course_title }}</p><p class="text-xs text-slate-500">{{ formatDate(certificate.issued_at, locale) }}</p></div><OperationStatusBadge group="certificateStatus" :status="certificate.status" /></RouterLink></div><PaginationNav v-if="!loading && !error && meta?.last_page > 1" :current-page="meta.current_page" :last-page="meta.last_page" @change="page" /></div></template>
