<script setup>
import { onMounted, ref } from 'vue'; import { useRoute, useRouter } from 'vue-router'; import { useI18n } from 'vue-i18n'; import { useAuthStore } from '../stores/auth';
import { downloadOperationalCertificate, fetchOperationalCertificate, reissueOperationalCertificate, revokeOperationalCertificate } from '../api/admin-operations'; import { formatDate } from '../utils/catalog';
import PageHeading from '../components/ui/PageHeading.vue'; import BaseAlert from '../components/ui/BaseAlert.vue'; import BaseButton from '../components/ui/BaseButton.vue'; import LoadingState from '../components/ui/LoadingState.vue'; import OperationStatusBadge from '../components/admin/OperationStatusBadge.vue'; import OperationReasonDialog from '../components/admin/OperationReasonDialog.vue';
const route = useRoute(); const router = useRouter(); const auth = useAuthStore(); const { t, locale } = useI18n(); const item = ref(null); const loading = ref(true); const busy = ref(false); const error = ref(null); const reasonOpen = ref(false);
async function load() { loading.value = true; error.value = null; try { item.value = await fetchOperationalCertificate(route.params.id); } catch (failure) { error.value = failure; } finally { loading.value = false; } }
onMounted(load);
async function revoke(reason) { if (busy.value || item.value?.status !== 'issued') return; busy.value = true; error.value = null; try { await revokeOperationalCertificate(item.value.id, reason); reasonOpen.value = false; item.value = await fetchOperationalCertificate(item.value.id); } catch (failure) { error.value = failure; } finally { busy.value = false; } }
async function reissue() { if (busy.value || item.value?.status !== 'revoked' || !window.confirm(t('operations.reissueConfirm'))) return; busy.value = true; error.value = null; try { const created = await reissueOperationalCertificate(item.value.id); await router.push({ name: 'admin.certificates.show', params: { id: created.id }, query: { reissued: 1 } }); } catch (failure) { error.value = failure; } finally { busy.value = false; } }
async function download() { if (busy.value) return; busy.value = true; error.value = null; try { await downloadOperationalCertificate(item.value.id); } catch (failure) { error.value = failure; } finally { busy.value = false; } }
</script>
<template><div class="mx-auto max-w-4xl space-y-6" :dir="locale === 'ar' ? 'rtl' : 'ltr'"><RouterLink :to="{ name: 'admin.certificates.index' }" class="font-bold text-brand">{{ t('operations.back') }}</RouterLink><LoadingState v-if="loading" /><BaseAlert v-else-if="error && !item" tone="danger">{{ t('operations.loadError') }}</BaseAlert><template v-else-if="item"><PageHeading :title="item.certificate_number" /><BaseAlert v-if="route.query.reissued" tone="success">{{ t('operations.newCertificate') }}</BaseAlert><BaseAlert v-if="error" tone="danger">{{ t('operations.saveError') }}</BaseAlert><section class="grid gap-4 rounded-3xl border bg-white p-6 text-sm sm:grid-cols-2"><div><p>{{ t('operations.student') }}: <strong>{{ item.student_name }}</strong></p><p>{{ t('operations.course') }}: <strong>{{ item.course_title }}</strong></p><p>{{ t('operations.issuedAt') }}: {{ formatDate(item.issued_at, locale) }}</p></div><div class="space-y-2"><OperationStatusBadge group="certificateStatus" :status="item.status" /><p v-if="item.revoked_at">{{ t('operations.revokedAt') }}: {{ formatDate(item.revoked_at, locale) }}</p><p v-if="item.revocation_reason">{{ t('operations.revokedReason') }}: {{ item.revocation_reason }}</p><a v-if="item.verification_url" :href="item.verification_url" target="_blank" rel="noopener noreferrer" class="block font-bold text-brand underline">{{ t('operations.verification') }}</a></div></section><div class="flex flex-wrap gap-3"><BaseButton variant="secondary" :loading="busy" @click="download">{{ t('operations.pdf') }}</BaseButton><BaseButton v-if="item.status === 'issued' && auth.can('certificates.revoke')" :disabled="busy" @click="reasonOpen = true">{{ t('operations.revoke') }}</BaseButton><BaseButton v-if="item.status === 'revoked' && auth.can('certificates.issue')" :loading="busy" @click="reissue">{{ t('operations.reissue') }}</BaseButton></div><OperationReasonDialog :open="reasonOpen" :title="t('operations.revokeConfirm')" :busy="busy" :error="error" @confirm="revoke" @cancel="reasonOpen = false" /></template></div></template>
