<script setup>
import { reactive, ref, watch } from 'vue'; import { useRoute, useRouter } from 'vue-router'; import { useI18n } from 'vue-i18n';
import { fetchModerationReviews } from '../api/admin-operations'; import { formatDate } from '../utils/catalog';
import { fetchAdminCourse, fetchAdminCourses } from '../api/admin';
import AsyncResourceSelect from '../components/ui/AsyncResourceSelect.vue';
import PageHeading from '../components/ui/PageHeading.vue'; import BaseAlert from '../components/ui/BaseAlert.vue'; import LoadingState from '../components/ui/LoadingState.vue'; import EmptyState from '../components/ui/EmptyState.vue'; import PaginationNav from '../components/ui/PaginationNav.vue'; import OperationStatusBadge from '../components/admin/OperationStatusBadge.vue';
const route = useRoute(); const router = useRouter(); const { t, locale } = useI18n(); const filters = reactive({ status: 'pending', course_id: '' }); const items = ref([]); const meta = ref(null); const loading = ref(true); const error = ref(null); let sequence = 0;
async function load() { const current = ++sequence; loading.value = true; error.value = null; filters.status = String(route.query.status ?? 'pending'); filters.course_id = String(route.query.course_id ?? ''); try { const result = await fetchModerationReviews({ page: Number(route.query.page) || 1, status: filters.status, ...(filters.course_id ? { course_id: filters.course_id } : {}) }); if (current === sequence) { items.value = result.items; meta.value = result.meta; } } catch (failure) { if (current === sequence) error.value = failure; } finally { if (current === sequence) loading.value = false; } }
watch(() => route.query, load, { immediate: true, deep: true });
function apply() { router.push({ name: 'admin.reviews.index', query: { status: filters.status, ...(filters.course_id ? { course_id: filters.course_id } : {}) } }); }
function page(value) { router.push({ name: 'admin.reviews.index', query: { ...route.query, page: value } }); }
</script>
<template><div class="space-y-6" :dir="locale === 'ar' ? 'rtl' : 'ltr'"><PageHeading :title="t('operations.reviews')" /><form class="grid gap-3 rounded-3xl border bg-white p-4 sm:grid-cols-3" @submit.prevent="apply"><div><label class="mb-2 block text-sm font-bold" for="review-status">{{ t('operations.status') }}</label><select id="review-status" v-model="filters.status" class="min-h-11 w-full rounded-xl border px-4"><option v-for="status in ['pending', 'published', 'rejected', 'hidden']" :key="status" :value="status">{{ t(`operations.reviewStatus.${status}`) }}</option></select></div><AsyncResourceSelect v-model="filters.course_id" id="review-course" :loader="fetchAdminCourses" :resolver="fetchAdminCourse" :label="t('operations.course')" /><button type="submit" class="min-h-11 self-end rounded-xl bg-brand px-5 font-bold text-white">{{ t('operations.filter') }}</button></form><LoadingState v-if="loading" /><BaseAlert v-else-if="error" tone="danger">{{ t('operations.loadError') }}</BaseAlert><EmptyState v-else-if="!items.length" :title="t('operations.empty')" /><div v-else class="grid gap-3"><RouterLink v-for="review in items" :key="review.id" :to="{ name: 'admin.reviews.show', params: { id: review.id } }" class="grid gap-2 rounded-2xl border bg-white p-5 hover:border-brand sm:grid-cols-[1fr_auto]"><div><h2 class="font-black">{{ review.course?.title }}</h2><p class="text-sm text-slate-600">{{ review.reviewer?.name }} · {{ review.rating }}/5 · {{ formatDate(review.submitted_at, locale) }}</p><p class="mt-2 line-clamp-2 text-sm">{{ review.title }} {{ review.body }}</p></div><OperationStatusBadge group="reviewStatus" :status="review.status" /></RouterLink></div><PaginationNav v-if="!loading && !error && meta?.last_page > 1" :current-page="meta.current_page" :last-page="meta.last_page" @change="page" /></div></template>
