<script setup>
import { reactive, ref, watch } from 'vue'; import { useRoute, useRouter } from 'vue-router'; import { useI18n } from 'vue-i18n';
import { fetchOperationalOrder, fetchOperationalOrders, fetchOperationalPayments } from '../api/admin-operations'; import { formatDate } from '../utils/catalog';
import AsyncResourceSelect from '../components/ui/AsyncResourceSelect.vue';
import PageHeading from '../components/ui/PageHeading.vue'; import BaseAlert from '../components/ui/BaseAlert.vue'; import LoadingState from '../components/ui/LoadingState.vue'; import EmptyState from '../components/ui/EmptyState.vue'; import PaginationNav from '../components/ui/PaginationNav.vue'; import OperationStatusBadge from '../components/admin/OperationStatusBadge.vue';
const route = useRoute(); const router = useRouter(); const { t, locale } = useI18n(); const supportArea = route.path.startsWith('/sales-support');
const listName = supportArea ? 'support.payments.index' : 'admin.payments.index'; const detailName = supportArea ? 'support.payments.show' : 'admin.payments.show';
const filters = reactive({ status: 'pending_review', order_id: '' }); const items = ref([]); const meta = ref(null); const loading = ref(true); const error = ref(null); let sequence = 0;
async function load() { const current = ++sequence; loading.value = true; error.value = null; filters.status = String(route.query.status ?? 'pending_review'); filters.order_id = String(route.query.order_id ?? ''); try { const result = await fetchOperationalPayments({ page: Number(route.query.page) || 1, status: filters.status, ...(filters.order_id ? { order_id: filters.order_id } : {}) }); if (current === sequence) { items.value = result.items; meta.value = result.meta; } } catch (failure) { if (current === sequence) error.value = failure; } finally { if (current === sequence) loading.value = false; } }
watch(() => route.query, load, { immediate: true, deep: true });
function apply() { router.push({ name: listName, query: { status: filters.status, ...(filters.order_id ? { order_id: filters.order_id } : {}) } }); }
function page(value) { router.push({ name: listName, query: { ...route.query, page: value } }); }
</script>
<template><div class="space-y-6" :dir="locale === 'ar' ? 'rtl' : 'ltr'"><PageHeading :title="t('operations.payments')" /><form class="grid gap-3 rounded-3xl border bg-white p-4 sm:grid-cols-3" @submit.prevent="apply"><div><label class="mb-2 block text-sm font-bold" for="payment-status">{{ t('operations.status') }}</label><select id="payment-status" v-model="filters.status" class="min-h-11 w-full rounded-xl border px-4"><option v-for="status in ['pending_review', 'paid', 'rejected']" :key="status" :value="status">{{ t(`operations.paymentStatus.${status}`) }}</option></select></div><AsyncResourceSelect v-model="filters.order_id" id="payment-order" :loader="fetchOperationalOrders" :resolver="fetchOperationalOrder" :label="t('operations.orderId')" /><button type="submit" class="min-h-11 self-end rounded-xl bg-brand px-5 font-bold text-white">{{ t('operations.filter') }}</button></form><LoadingState v-if="loading" /><BaseAlert v-else-if="error" tone="danger">{{ t('operations.loadError') }} <button class="underline" @click="load">{{ t('operations.retry') }}</button></BaseAlert><EmptyState v-else-if="!items.length" :title="t('operations.empty')" /><div v-else class="grid gap-3"><RouterLink v-for="payment in items" :key="payment.id" :to="{ name: detailName, params: { id: payment.id } }" class="flex flex-wrap items-center justify-between gap-3 rounded-2xl border bg-white p-5 hover:border-brand"><div><p class="font-black">{{ payment.order_number ?? `#${payment.order_id}` }}</p><p class="text-sm text-slate-600">{{ payment.transaction_id || '—' }} · {{ formatDate(payment.created_at, locale) }}</p></div><OperationStatusBadge group="paymentStatus" :status="payment.status" /><bdi class="font-black">{{ payment.amount }} {{ payment.currency }}</bdi></RouterLink></div><PaginationNav v-if="!loading && !error && meta?.last_page > 1" :current-page="meta.current_page" :last-page="meta.last_page" @change="page" /></div></template>
