<script setup>
import { onMounted, ref } from 'vue'; import { useRoute } from 'vue-router'; import { useI18n } from 'vue-i18n'; import { useAuthStore } from '../stores/auth';
import { approveOperationalPayment, downloadOperationalProof, fetchOperationalPayment, rejectOperationalPayment } from '../api/admin-operations'; import { formatDate } from '../utils/catalog';
import PageHeading from '../components/ui/PageHeading.vue'; import BaseAlert from '../components/ui/BaseAlert.vue'; import BaseButton from '../components/ui/BaseButton.vue'; import LoadingState from '../components/ui/LoadingState.vue'; import OperationStatusBadge from '../components/admin/OperationStatusBadge.vue'; import OperationReasonDialog from '../components/admin/OperationReasonDialog.vue';
const route = useRoute(); const auth = useAuthStore(); const { t, locale } = useI18n(); const supportArea = route.path.startsWith('/sales-support'); const listName = supportArea ? 'support.payments.index' : 'admin.payments.index'; const orderName = supportArea ? 'support.orders.show' : 'admin.orders.show';
const item = ref(null); const loading = ref(true); const busy = ref(false); const error = ref(null); const reasonOpen = ref(false);
async function load() { loading.value = true; error.value = null; try { item.value = await fetchOperationalPayment(route.params.id); } catch (failure) { error.value = failure; } finally { loading.value = false; } }
onMounted(load);
async function approve() { if (busy.value || item.value?.status !== 'pending_review' || !window.confirm(t('operations.approveConfirm'))) return; busy.value = true; error.value = null; try { await approveOperationalPayment(item.value.id); item.value = await fetchOperationalPayment(item.value.id); } catch (failure) { error.value = failure; await fetchOperationalPayment(route.params.id).then((fresh) => { item.value = fresh; }).catch(() => {}); } finally { busy.value = false; } }
async function reject(reason) { if (busy.value || item.value?.status !== 'pending_review') return; busy.value = true; error.value = null; try { await rejectOperationalPayment(item.value.id, reason); reasonOpen.value = false; item.value = await fetchOperationalPayment(item.value.id); } catch (failure) { error.value = failure; await fetchOperationalPayment(route.params.id).then((fresh) => { item.value = fresh; }).catch(() => {}); } finally { busy.value = false; } }
async function proof() { if (busy.value) return; busy.value = true; error.value = null; try { await downloadOperationalProof(item.value.id); } catch (failure) { error.value = failure; } finally { busy.value = false; } }
</script>
<template><div class="mx-auto max-w-4xl space-y-6" :dir="locale === 'ar' ? 'rtl' : 'ltr'"><RouterLink :to="{ name: listName }" class="font-bold text-brand">{{ t('operations.back') }}</RouterLink><LoadingState v-if="loading" /><BaseAlert v-else-if="error && !item" tone="danger">{{ t('operations.loadError') }}</BaseAlert><template v-else-if="item"><PageHeading :title="`${t('operations.payments')} #${item.id}`" /><BaseAlert v-if="error" tone="danger">{{ t('operations.saveError') }} {{ error?.errors?.payment?.[0] ?? error?.errors?.order?.[0] ?? '' }}</BaseAlert><section class="grid gap-4 rounded-3xl border bg-white p-6 sm:grid-cols-2"><div class="space-y-2"><OperationStatusBadge group="paymentStatus" :status="item.status" /><p>{{ t('operations.paymentMethod') }}: {{ item.method }}</p><p>{{ t('operations.reference') }}: {{ item.transaction_id || '—' }}</p><p>{{ t('operations.created') }}: {{ formatDate(item.created_at, locale) }}</p></div><div class="space-y-2"><p class="text-2xl font-black"><bdi>{{ item.amount }} {{ item.currency }}</bdi></p><p v-if="item.paid_at">{{ t('operations.paidAt') }}: {{ formatDate(item.paid_at, locale) }}</p><p v-if="item.rejection_reason">{{ t('operations.rejectionReason') }}: {{ item.rejection_reason }}</p><RouterLink v-if="auth.can('orders.view')" :to="{ name: orderName, params: { id: item.order_id } }" class="block font-bold text-brand underline">{{ t('operations.orderLink') }}: {{ item.order_number }}</RouterLink></div></section><div class="flex flex-wrap gap-3"><BaseButton v-if="item.proof_available" variant="secondary" :loading="busy" @click="proof">{{ t('operations.proof') }}</BaseButton><BaseButton v-if="item.status === 'pending_review' && auth.can('payments.manage')" :loading="busy" @click="approve">{{ t('operations.approval') }}</BaseButton><BaseButton v-if="item.status === 'pending_review' && auth.can('payments.manage')" variant="secondary" :disabled="busy" @click="reasonOpen = true">{{ t('operations.rejection') }}</BaseButton></div><OperationReasonDialog :open="reasonOpen" :title="t('operations.rejection')" :busy="busy" :error="error" :min-length="1" @confirm="reject" @cancel="reasonOpen = false" /></template></div></template>
