<script setup>
import { onMounted, reactive, ref } from 'vue'; import { useRoute } from 'vue-router'; import { useI18n } from 'vue-i18n'; import { useAuthStore } from '../stores/auth';
import { assignOperationalTicket, downloadOperationalAttachment, fetchOperationalTicket, fetchOperationalTicketMessages, postOperationalTicketMessage, updateOperationalTicket } from '../api/admin-operations';
import { fetchSupportStaff, resolveSupportStaff } from '../api/admin-users';
import { attachmentExtensions, hasAttachmentErrors, ticketCategories, ticketPriorities, ticketFormData, validateAttachments } from '../utils/support'; import { formatDate } from '../utils/catalog';
import PageHeading from '../components/ui/PageHeading.vue'; import BaseAlert from '../components/ui/BaseAlert.vue'; import BaseButton from '../components/ui/BaseButton.vue'; import LoadingState from '../components/ui/LoadingState.vue'; import PaginationNav from '../components/ui/PaginationNav.vue'; import OperationStatusBadge from '../components/admin/OperationStatusBadge.vue';
import AsyncResourceSelect from '../components/ui/AsyncResourceSelect.vue';
const route = useRoute(); const auth = useAuthStore(); const { t, locale } = useI18n(); const supportArea = route.path.startsWith('/sales-support'); const listName = supportArea ? 'support.tickets' : 'admin.tickets.index';
const ticket = ref(null); const messages = ref([]); const meta = ref(null); const loading = ref(true); const busy = ref(false); const error = ref(null); const stale = ref(false); const fileError = ref(null); const downloadingId = ref(null); const messagePage = ref(1);
const form = reactive({ category: '', priority: '', assigned_to: '', body: '', files: [] }); const mode = ref('public'); const fileInput = ref(null);
async function loadMessages(page = 1) { const result = await fetchOperationalTicketMessages(route.params.id, page); messages.value = result.items; meta.value = result.meta; messagePage.value = page; }
async function refresh() { ticket.value = await fetchOperationalTicket(route.params.id); form.category = ticket.value.category; form.priority = ticket.value.priority; form.assigned_to = ticket.value.assignee?.id ?? ''; await loadMessages(messagePage.value); }
async function load() { loading.value = true; error.value = null; try { await refresh(); } catch (failure) { error.value = failure; } finally { loading.value = false; } }
onMounted(load);
async function mutate(operation, newestMessage = false) { if (busy.value || !ticket.value) return; busy.value = true; error.value = null; stale.value = false; try { await operation(); await refresh(); if (newestMessage && meta.value?.last_page > 1) await loadMessages(meta.value.last_page); } catch (failure) { error.value = failure; if (failure.status === 422 && failure.errors?.expected_updated_at) { stale.value = true; await refresh().catch(() => {}); } } finally { busy.value = false; } }
function status(target) { if (!window.confirm(t('operations.statusConfirm'))) return; mutate(() => updateOperationalTicket(ticket.value.id, { status: target, expected_updated_at: ticket.value.updated_at })); }
function saveMetadata() { mutate(() => updateOperationalTicket(ticket.value.id, { category: form.category, priority: form.priority, expected_updated_at: ticket.value.updated_at })); }
function assign() { if (!Number.isInteger(Number(form.assigned_to)) || Number(form.assigned_to) < 1) return; mutate(() => assignOperationalTicket(ticket.value.id, { assigned_to: Number(form.assigned_to), expected_updated_at: ticket.value.updated_at })); }
function selectFiles(event) { form.files = Array.from(event.target.files ?? []); fileError.value = validateAttachments(form.files); }
async function send() { if (busy.value || !form.body.trim() || form.body.length > 10000 || ticket.value?.status === 'closed') return; fileError.value = validateAttachments(form.files); if (fileError.value) return; await mutate(() => postOperationalTicketMessage(ticket.value.id, ticketFormData({ body: form.body.trim(), is_internal: mode.value === 'internal' ? 1 : 0 }, form.files)), true); if (!error.value) { form.body = ''; form.files = []; if (fileInput.value) fileInput.value.value = ''; } }
async function download(id) { if (downloadingId.value !== null) return; downloadingId.value = id; error.value = null; try { await downloadOperationalAttachment(id); } catch (failure) { error.value = failure; } finally { downloadingId.value = null; } }
</script>
<template><div class="mx-auto max-w-6xl space-y-6" :dir="locale === 'ar' ? 'rtl' : 'ltr'"><RouterLink :to="{ name: listName }" class="font-bold text-brand">{{ t('operations.back') }}</RouterLink><LoadingState v-if="loading" /><BaseAlert v-else-if="error && !ticket" tone="danger">{{ t('operations.loadError') }} <button class="underline" @click="load">{{ t('operations.retry') }}</button></BaseAlert><template v-else-if="ticket"><PageHeading :title="ticket.subject" :description="ticket.ticket_number" /><BaseAlert v-if="stale" tone="danger">{{ t('operations.stale') }}</BaseAlert><BaseAlert v-else-if="error" tone="danger">{{ t('operations.saveError') }} {{ error?.errors?.status?.[0] ?? '' }}</BaseAlert>
            <section class="grid gap-4 rounded-3xl border bg-white p-5 text-sm sm:grid-cols-2 lg:grid-cols-4"><div><span class="text-slate-500">{{ t('operations.student') }}</span><p class="font-bold">{{ ticket.student?.name }}</p></div><div><OperationStatusBadge group="ticketStatus" :status="ticket.status" /><p class="mt-2">{{ formatDate(ticket.updated_at, locale) }}</p></div><div><span class="text-slate-500">{{ t('operations.category') }}</span><p class="font-bold">{{ t(`operations.ticketCategory.${ticket.category}`) }}</p></div><div><span class="text-slate-500">{{ t('operations.priority') }}</span><p class="font-bold">{{ t(`operations.ticketPriority.${ticket.priority}`) }}</p></div></section>
            <section v-if="auth.can('support_tickets.manage')" class="space-y-4 rounded-3xl border bg-white p-5"><h2 class="font-black">{{ t('operations.updateTicket') }}</h2><div class="flex flex-wrap gap-3"><select v-model="form.category" :aria-label="t('operations.category')" class="min-h-11 rounded-xl border px-3"><option v-for="value in ticketCategories" :key="value" :value="value">{{ t(`operations.ticketCategory.${value}`) }}</option></select><select v-model="form.priority" :aria-label="t('operations.priority')" class="min-h-11 rounded-xl border px-3"><option v-for="value in ticketPriorities" :key="value" :value="value">{{ t(`operations.ticketPriority.${value}`) }}</option></select><BaseButton variant="secondary" :loading="busy" @click="saveMetadata">{{ t('operations.updateTicket') }}</BaseButton></div><div class="grid gap-3 sm:grid-cols-[minmax(0,1fr)_auto] sm:items-end"><AsyncResourceSelect v-model="form.assigned_to" id="ticket-assignee" :loader="fetchSupportStaff" :resolver="resolveSupportStaff" :initial-option="ticket.assignee" :label="t('operations.assignee')" /><BaseButton variant="secondary" :loading="busy" :disabled="!form.assigned_to" @click="assign">{{ t('operations.assignee') }}</BaseButton></div><p v-if="error?.errors?.assigned_to" role="alert" class="text-sm text-red-700">{{ error.errors.assigned_to[0] }}</p><div class="flex flex-wrap gap-2"><BaseButton v-if="['open', 'waiting_for_student'].includes(ticket.status)" variant="secondary" :loading="busy" @click="status('in_progress')">{{ t('operations.inProgress') }}</BaseButton><BaseButton v-if="['open', 'in_progress'].includes(ticket.status)" variant="secondary" :loading="busy" @click="status('waiting_for_student')">{{ t('operations.waiting') }}</BaseButton><BaseButton v-if="['open', 'in_progress', 'waiting_for_student'].includes(ticket.status)" :loading="busy" @click="status('resolved')">{{ t('operations.resolve') }}</BaseButton><BaseButton v-if="ticket.status !== 'closed'" variant="secondary" :loading="busy" @click="status('closed')">{{ t('operations.close') }}</BaseButton><BaseButton v-if="['closed', 'resolved'].includes(ticket.status)" variant="secondary" :loading="busy" @click="status('open')">{{ t('operations.reopen') }}</BaseButton></div></section>
            <section class="space-y-4"><h2 class="text-xl font-black">{{ t('operations.messages') }}</h2><p v-if="!messages.length" class="rounded-2xl border bg-white p-5 text-sm">{{ t('operations.noMessages') }}</p><ol v-else class="space-y-3"><li v-for="message in messages" :key="message.id" class="rounded-2xl border p-5" :class="message.is_internal ? 'border-amber-400 bg-amber-50' : 'border-slate-200 bg-white'"><div class="flex flex-wrap justify-between gap-3 text-sm"><strong>{{ message.is_internal ? t('operations.internalNote') : message.author?.id === ticket.student?.id ? t('operations.studentMessage') : t('operations.staffMessage') }} · {{ message.author?.name }}</strong><span>{{ formatDate(message.created_at, locale) }}</span></div><p class="mt-3 whitespace-pre-wrap break-words text-sm leading-7">{{ message.body }}</p><div v-if="message.attachments?.length" class="mt-3 flex flex-wrap gap-2"><button v-for="file in message.attachments" :key="file.id" type="button" class="min-h-11 rounded-xl border bg-white px-3 text-sm font-bold text-brand" :disabled="downloadingId !== null" @click="download(file.id)">{{ t('operations.download') }}: {{ file.filename }}</button></div></li></ol><PaginationNav v-if="meta?.last_page > 1" :current-page="meta.current_page" :last-page="meta.last_page" @change="loadMessages" /></section>
            <section v-if="auth.can('support_tickets.reply') && ticket.status !== 'closed'" class="space-y-4 rounded-3xl border bg-white p-5"><div class="flex flex-wrap gap-3"><button type="button" class="min-h-11 rounded-xl border px-4 font-bold" :class="mode === 'public' ? 'border-brand text-brand' : 'border-slate-300'" @click="mode = 'public'">{{ t('operations.publicReply') }}</button><button type="button" class="min-h-11 rounded-xl border px-4 font-bold" :class="mode === 'internal' ? 'border-amber-500 bg-amber-50 text-amber-950' : 'border-slate-300'" @click="mode = 'internal'">{{ t('operations.internalNote') }}</button></div><BaseAlert v-if="mode === 'internal'">{{ t('operations.internalNote') }}</BaseAlert><form class="space-y-3" @submit.prevent="send"><label for="staff-message" class="block text-sm font-bold">{{ t('operations.message') }}</label><textarea id="staff-message" v-model="form.body" required rows="4" maxlength="10000" class="w-full rounded-xl border px-4 py-3" :disabled="busy" /><label for="staff-files" class="block text-sm font-bold">{{ t('operations.addFiles') }}</label><input id="staff-files" ref="fileInput" type="file" multiple :accept="attachmentExtensions" class="w-full rounded-xl border px-3 py-2" :disabled="busy" @change="selectFiles"><p v-if="fileError || hasAttachmentErrors(error?.errors)" role="alert" class="text-sm text-red-700">{{ t('operations.uploadFailure') }}</p><BaseButton type="submit" :loading="busy">{{ t(mode === 'internal' ? 'operations.saveInternal' : 'operations.sendPublic') }}</BaseButton></form></section>
            <section v-if="ticket.activities?.length" class="rounded-3xl border bg-white p-5"><h2 class="font-black">{{ t('operations.activity') }}</h2><ol class="mt-3 space-y-2 text-sm"><li v-for="entry in ticket.activities" :key="entry.id">{{ entry.actor_name }} · {{ entry.event_type }} · {{ formatDate(entry.created_at, locale) }}</li></ol></section>
        </template></div></template>
