<script setup>
import { onMounted, ref } from 'vue';
import { useRoute } from 'vue-router';
import { useI18n } from 'vue-i18n';
import { useAuthStore } from '../stores/auth';
import { fetchOperationalOrder, provisionOrderAccess } from '../api/admin-operations';
import { formatAmount, formatDate } from '../utils/catalog';
import PageHeading from '../components/ui/PageHeading.vue'; import BaseAlert from '../components/ui/BaseAlert.vue'; import BaseButton from '../components/ui/BaseButton.vue'; import LoadingState from '../components/ui/LoadingState.vue'; import OperationStatusBadge from '../components/admin/OperationStatusBadge.vue';
const route = useRoute(); const auth = useAuthStore(); const { t, locale } = useI18n(); const supportArea = route.path.startsWith('/sales-support');
const listName = supportArea ? 'support.orders' : 'admin.orders.index'; const paymentName = supportArea ? 'support.payments.show' : 'admin.payments.show';
const item = ref(null); const loading = ref(true); const busy = ref(false); const error = ref(null);
async function load() { loading.value = true; error.value = null; try { item.value = await fetchOperationalOrder(route.params.id); } catch (failure) { error.value = failure; } finally { loading.value = false; } }
onMounted(load);
async function provision() { if (busy.value || item.value?.status !== 'paid' || !window.confirm(t('operations.provisionConfirm'))) return; busy.value = true; error.value = null; try { await provisionOrderAccess(item.value.id); item.value = await fetchOperationalOrder(item.value.id); } catch (failure) { error.value = failure; await fetchOperationalOrder(route.params.id).then((fresh) => { item.value = fresh; }).catch(() => {}); } finally { busy.value = false; } }
</script>
<template>
    <div class="mx-auto max-w-5xl space-y-6" :dir="locale === 'ar' ? 'rtl' : 'ltr'"><RouterLink :to="{ name: listName }" class="text-sm font-bold text-brand">{{ t('operations.back') }}</RouterLink><LoadingState v-if="loading" /><BaseAlert v-else-if="error && !item" tone="danger">{{ t('operations.loadError') }} <button class="font-bold underline" @click="load">{{ t('operations.retry') }}</button></BaseAlert>
        <template v-else-if="item"><PageHeading :title="item.order_number" :description="t('operations.snapshot')" /><BaseAlert v-if="error" tone="danger">{{ t('operations.saveError') }}</BaseAlert><BaseAlert v-if="item.status === 'paid'">{{ t('operations.provisionNote') }}</BaseAlert>
            <section class="grid gap-4 rounded-3xl border border-slate-200 bg-white p-5 text-sm sm:grid-cols-2"><div><span class="text-slate-500">{{ t('operations.customer') }}</span><p class="font-bold">{{ item.customer_name }}</p><p>{{ item.customer_email }}</p><p>{{ item.customer_phone }}</p></div><div class="space-y-2"><OperationStatusBadge group="orderStatus" :status="item.status" /><p>{{ t('operations.placed') }}: {{ formatDate(item.placed_at, locale) }}</p><p v-if="item.paid_at">{{ t('operations.paidAt') }}: {{ formatDate(item.paid_at, locale) }}</p><p class="text-xl font-black"><bdi>{{ formatAmount(item.total, locale) }} {{ item.currency }}</bdi></p></div></section>
            <section class="space-y-4 rounded-3xl border border-slate-200 bg-white p-5"><h2 class="text-lg font-black">{{ t('operations.items') }}</h2><p class="text-xs text-slate-500">{{ t('operations.snapshotNote') }}</p><article v-for="line in item.items ?? []" :key="line.id" class="rounded-2xl border border-slate-200 p-4"><div class="flex flex-wrap justify-between gap-3"><div><h3 class="font-bold">{{ line.title }}</h3><p class="text-sm text-slate-600">{{ t('operations.quantity') }}: {{ line.quantity }} · {{ t('operations.duration') }}: {{ line.access_duration_days === null ? t('operations.lifetime') : t('operations.days', { count: line.access_duration_days }) }}</p></div><bdi class="font-black">{{ formatAmount(line.total, locale) }} {{ item.currency }}</bdi></div><ol v-if="line.package_courses?.length" class="mt-3 list-inside list-decimal text-sm text-slate-700"><li v-for="course in line.package_courses" :key="course.id">{{ course.course_title }}</li></ol></article></section>
            <section class="space-y-3 rounded-3xl border border-slate-200 bg-white p-5"><h2 class="text-lg font-black">{{ t('operations.payments') }}</h2><p v-if="!item.payments?.length" class="text-sm text-slate-500">{{ t('operations.noPayment') }}</p><div v-for="payment in item.payments ?? []" :key="payment.id" class="flex flex-wrap items-center justify-between gap-3 rounded-xl border border-slate-200 p-4"><RouterLink v-if="auth.can('payments.view')" :to="{ name: paymentName, params: { id: payment.id } }" class="font-bold text-brand underline">{{ payment.transaction_id || `#${payment.id}` }} · <bdi>{{ payment.amount }} {{ payment.currency }}</bdi></RouterLink><span v-else>{{ payment.transaction_id || `#${payment.id}` }} · <bdi>{{ payment.amount }} {{ payment.currency }}</bdi></span><OperationStatusBadge group="paymentStatus" :status="payment.status" /></div></section>
            <BaseButton v-if="item.status === 'paid' && auth.can('orders.manage')" :loading="busy" @click="provision">{{ t('operations.provision') }}</BaseButton>
        </template>
    </div>
</template>
